/*
###############################################################
#  Generated by:      Cadence Innovus 16.11-s067_1
#  OS:                Linux x86_64(Host ID linrack6.ee.columbia.edu)
#  Generated on:      Sat Jan  7 18:58:14 2017
#  Design:            SPI_slave_48bit
#  Command:           saveNetlist ./OUTPUT_0107_SPI_00_NOM5/0107_SPI_00_NOM5.phy.v -phys -excludeLeafCell -excludeCellInst {FILL1 FILL2 FILL4 FILL8 FILL16 FILL32 FILL64}
###############################################################
*/
module SNPS_CLOCK_GATE_HIGH_SPI_slave_48bit_0 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   // Module instantiations
   CKLNQD2 latch (
	.CP(CLK),
	.E(EN),
	.Q(ENCLK),
	.TE(TE));
endmodule

module SNPS_CLOCK_GATE_HIGH_SPI_slave_48bit_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   // Module instantiations
   CKLNQD2 latch (
	.CP(CLK),
	.E(EN),
	.Q(ENCLK),
	.TE(TE));
endmodule

module SPI_slave_48bit_phy (
	din, 
	clk, 
	reset, 
	presetval, 
	load, 
	wr, 
	dout, 
	data);
   input din;
   input clk;
   input reset;
   input [47:0] presetval;
   input load;
   input wr;
   output dout;
   output [47:0] data;

   // Internal wires
   wire FE_PHN383_FE_OFN56_n48;
   wire FE_PHN382_shift_37;
   wire FE_PHN381_shift_33;
   wire FE_PHN380_n11;
   wire FE_PHN379_n8;
   wire FE_PHN378_N22;
   wire FE_PHN377_N28;
   wire FE_PHN376_shift_30;
   wire FE_PHN375_shift_43;
   wire FE_PHN374_shift_17;
   wire FE_PHN373_shift_11;
   wire FE_PHN372_shift_34;
   wire FE_PHN371_shift_44;
   wire FE_PHN370_shift_46;
   wire FE_PHN369_shift_13;
   wire FE_PHN368_presetval_8;
   wire FE_PHN367_FE_OFN27_data_20;
   wire FE_PHN366_FE_OFN3_data_44;
   wire FE_PHN365_FE_OFN43_data_4;
   wire FE_PHN364_shift_33;
   wire FE_PHN363_shift_35;
   wire FE_PHN362_FE_OFN32_data_15;
   wire FE_PHN361_shift_22;
   wire FE_PHN360_shift_41;
   wire FE_PHN359_shift_26;
   wire FE_PHN358_presetval_6;
   wire FE_PHN357_shift_28;
   wire FE_PHN356_shift_6;
   wire FE_PHN355_shift_5;
   wire FE_PHN354_shift_18;
   wire FE_PHN353_shift_1;
   wire FE_PHN352_shift_32;
   wire FE_PHN351_shift_39;
   wire FE_PHN350_shift_0;
   wire FE_PHN349_shift_27;
   wire FE_PHN348_shift_15;
   wire FE_PHN347_shift_20;
   wire FE_PHN346_shift_24;
   wire FE_PHN345_shift_7;
   wire FE_PHN344_shift_10;
   wire FE_PHN343_shift_21;
   wire FE_PHN342_shift_12;
   wire FE_PHN341_presetval_39;
   wire FE_PHN340_shift_2;
   wire FE_PHN339_shift_38;
   wire FE_PHN338_shift_42;
   wire FE_PHN337_FE_OFN72_n64;
   wire FE_PHN336_n62;
   wire FE_PHN335_shift_23;
   wire FE_PHN334_shift_19;
   wire FE_PHN333_shift_25;
   wire FE_PHN332_FE_OFN98_n90;
   wire FE_PHN331_n74;
   wire FE_PHN330_n66;
   wire FE_PHN329_FE_OFN110_n96;
   wire FE_PHN328_shift_31;
   wire FE_PHN327_shift_14;
   wire FE_PHN326_shift_29;
   wire FE_PHN325_shift_8;
   wire FE_PHN324_shift_45;
   wire FE_PHN323_shift_40;
   wire FE_PHN322_din;
   wire FE_PHN321_n72;
   wire FE_PHN320_n68;
   wire FE_PHN319_presetval_24;
   wire FE_PHN318_presetval_19;
   wire FE_PHN317_FE_OFN98_n90;
   wire FE_PHN316_n8;
   wire FE_PHN315_presetval_19;
   wire FE_PHN314_presetval_12;
   wire FE_PHN313_presetval_12;
   wire FE_PHN312_presetval_12;
   wire FE_PHN311_presetval_16;
   wire FE_PHN310_presetval_12;
   wire FE_PHN309_presetval_12;
   wire FE_PHN308_presetval_16;
   wire FE_PHN307_presetval_18;
   wire FE_PHN306_FE_OFN72_n64;
   wire FE_PHN305_shift_46;
   wire FE_PHN304_presetval_12;
   wire FE_PHN303_presetval_16;
   wire FE_PHN302_presetval_18;
   wire FE_PHN301_presetval_14;
   wire FE_PHN300_FE_OFN60_n52;
   wire FE_PHN299_presetval_12;
   wire FE_PHN298_shift_11;
   wire FE_PHN297_shift_16;
   wire FE_PHN296_shift_17;
   wire FE_PHN295_shift_34;
   wire FE_PHN294_FE_OFN92_n84;
   wire FE_PHN293_FE_OFN88_n80;
   wire FE_PHN292_FE_OFN98_n90;
   wire FE_PHN291_presetval_19;
   wire FE_PHN290_presetval_10;
   wire FE_PHN289_presetval_17;
   wire FE_PHN288_presetval_11;
   wire FE_PHN287_presetval_21;
   wire FE_PHN286_presetval_16;
   wire FE_PHN285_presetval_18;
   wire FE_PHN284_FE_OFN106_n98;
   wire FE_PHN283_FE_OFN64_n56;
   wire FE_PHN282_FE_OFN56_n48;
   wire FE_PHN281_presetval_1;
   wire FE_PHN280_presetval_5;
   wire FE_PHN279_presetval_13;
   wire FE_PHN278_presetval_7;
   wire FE_PHN277_presetval_9;
   wire FE_PHN276_presetval_15;
   wire FE_PHN275_presetval_0;
   wire FE_PHN274_presetval_8;
   wire FE_PHN273_presetval_20;
   wire FE_PHN272_n10;
   wire FE_PHN271_presetval_2;
   wire FE_PHN270_n12;
   wire FE_PHN269_presetval_6;
   wire FE_PHN268_presetval_16;
   wire FE_PHN267_presetval_19;
   wire FE_PHN266_presetval_15;
   wire FE_PHN265_FE_OFN56_n48;
   wire FE_PHN264_FE_OFN80_n72;
   wire FE_PHN263_presetval_16;
   wire FE_PHN262_FE_OFN76_n68;
   wire FE_PHN261_FE_OFN94_n86;
   wire FE_PHN260_FE_OFN68_n60;
   wire FE_PHN259_shift_44;
   wire FE_PHN258_presetval_16;
   wire FE_PHN257_presetval_15;
   wire FE_PHN256_n40;
   wire FE_PHN255_shift_7;
   wire FE_PHN254_FE_OFN88_n80;
   wire FE_PHN253_n16;
   wire FE_PHN252_n42;
   wire FE_PHN251_FE_OFN90_n82;
   wire FE_PHN250_presetval_41;
   wire FE_PHN249_presetval_28;
   wire FE_PHN248_FE_OFN82_n74;
   wire FE_PHN247_FE_OFN92_n84;
   wire FE_PHN246_FE_OFN58_n50;
   wire FE_PHN245_FE_OFN74_n66;
   wire FE_PHN244_presetval_34;
   wire FE_PHN243_FE_OFN70_n62;
   wire FE_PHN242_presetval_32;
   wire FE_PHN241_shift_13;
   wire FE_PHN240_presetval_19;
   wire FE_PHN239_shift_35;
   wire FE_PHN238_FE_OFN98_n90;
   wire FE_PHN237_FE_OFN64_n56;
   wire FE_PHN236_FE_OFN104_n96;
   wire FE_PHN235_n16;
   wire FE_PHN234_FE_OFN72_n64;
   wire FE_PHN233_FE_OFN106_n98;
   wire FE_PHN232_n14;
   wire FE_PHN231_n40;
   wire FE_PHN230_presetval_1;
   wire FE_PHN229_n18;
   wire FE_PHN228_presetval_11;
   wire FE_PHN227_presetval_0;
   wire FE_PHN226_presetval_9;
   wire FE_PHN225_FE_OFN102_n94;
   wire FE_PHN224_presetval_13;
   wire FE_PHN223_presetval_14;
   wire FE_PHN222_FE_OFN66_n58;
   wire FE_PHN221_FE_OFN84_n76;
   wire FE_PHN220_FE_OFN78_n70;
   wire FE_PHN219_presetval_10;
   wire FE_PHN218_FE_OFN100_n92;
   wire FE_PHN217_FE_OFN96_n88;
   wire FE_PHN216_presetval_17;
   wire FE_PHN215_presetval_23;
   wire FE_PHN214_FE_OFN86_n78;
   wire FE_PHN213_FE_OFN62_n54;
   wire FE_PHN212_presetval_21;
   wire FE_PHN211_presetval_35;
   wire FE_PHN210_presetval_31;
   wire FE_PHN209_presetval_29;
   wire FE_PHN208_presetval_39;
   wire FE_PHN207_presetval_24;
   wire FE_PHN206_presetval_40;
   wire FE_PHN205_presetval_17;
   wire FE_PHN204_presetval_11;
   wire FE_PHN203_presetval_10;
   wire FE_PHN202_presetval_14;
   wire FE_PHN201_presetval_13;
   wire FE_PHN200_presetval_6;
   wire FE_PHN199_presetval_1;
   wire FE_PHN198_presetval_0;
   wire FE_PHN197_presetval_9;
   wire FE_PHN196_presetval_7;
   wire FE_PHN195_presetval_5;
   wire FE_PHN194_presetval_18;
   wire FE_PHN193_presetval_2;
   wire FE_PHN192_presetval_8;
   wire FE_PHN191_presetval_12;
   wire FE_PHN190_presetval_20;
   wire FE_PHN189_shift_3;
   wire FE_PHN188_load;
   wire FE_PHN187_presetval_41;
   wire FE_PHN186_presetval_29;
   wire FE_PHN185_presetval_28;
   wire FE_PHN184_presetval_34;
   wire FE_PHN183_presetval_32;
   wire FE_PHN182_presetval_40;
   wire FE_PHN181_presetval_31;
   wire FE_PHN180_presetval_35;
   wire FE_PHN179_presetval_39;
   wire FE_PHN178_presetval_24;
   wire FE_PHN177_FE_OFN51_shift_4;
   wire FE_PHN176_presetval_4;
   wire FE_PHN175_shift_35;
   wire FE_PHN174_shift_47;
   wire FE_PHN173_shift_19;
   wire FE_PHN172_shift_13;
   wire FE_PHN171_shift_9;
   wire FE_PHN170_shift_5;
   wire FE_PHN169_shift_30;
   wire FE_PHN168_shift_7;
   wire FE_PHN167_shift_39;
   wire FE_PHN166_shift_26;
   wire FE_PHN165_shift_10;
   wire FE_PHN164_shift_42;
   wire FE_PHN163_shift_23;
   wire FE_PHN162_shift_36;
   wire FE_PHN161_shift_32;
   wire FE_PHN160_shift_44;
   wire FE_PHN159_shift_18;
   wire FE_PHN158_shift_43;
   wire FE_PHN157_shift_41;
   wire FE_PHN156_shift_22;
   wire FE_PHN155_shift_0;
   wire FE_PHN154_shift_12;
   wire FE_PHN153_shift_38;
   wire FE_PHN152_shift_24;
   wire FE_PHN151_shift_27;
   wire FE_PHN150_shift_29;
   wire FE_PHN149_shift_20;
   wire FE_PHN148_shift_37;
   wire FE_PHN147_shift_2;
   wire FE_PHN146_shift_15;
   wire FE_PHN145_shift_31;
   wire FE_PHN144_shift_45;
   wire FE_PHN143_shift_28;
   wire FE_PHN142_shift_14;
   wire FE_PHN141_shift_40;
   wire FE_PHN140_shift_25;
   wire FE_PHN139_shift_17;
   wire FE_PHN138_shift_1;
   wire FE_PHN137_shift_8;
   wire FE_PHN136_shift_16;
   wire FE_PHN135_shift_11;
   wire FE_PHN134_shift_46;
   wire FE_PHN133_shift_6;
   wire FE_PHN132_shift_33;
   wire FE_PHN131_shift_34;
   wire FE_PHN130_shift_21;
   wire FE_PHN129_presetval_30;
   wire FE_PHN128_presetval_37;
   wire FE_PHN127_presetval_38;
   wire FE_PHN126_presetval_27;
   wire FE_PHN125_presetval_43;
   wire FE_PHN124_presetval_25;
   wire FE_PHN123_presetval_36;
   wire FE_PHN122_presetval_42;
   wire FE_PHN121_presetval_44;
   wire FE_PHN120_presetval_26;
   wire FE_PHN119_presetval_46;
   wire FE_PHN118_presetval_33;
   wire FE_PHN117_presetval_47;
   wire FE_PHN116_presetval_22;
   wire FE_PHN115_presetval_45;
   wire FE_PHN114_presetval_3;
   wire FE_OFN112_n64;
   wire FE_OFN111_n83;
   wire FE_OFN110_n96;
   wire FE_OFN109_n113;
   wire FE_OFN108_n63;
   wire FE_OFN108_FE_OFN48_load;
   wire CTS_24;
   wire CTS_23;
   wire CTS_22;
   wire CTS_21;
   wire CTS_20;
   wire CTS_19;
   wire FE_OFN107_n113;
   wire FE_OFN106_n98;
   wire FE_OFN105_n97;
   wire FE_OFN104_n96;
   wire FE_OFN103_n95;
   wire FE_OFN102_n94;
   wire FE_OFN101_n93;
   wire FE_OFN100_n92;
   wire FE_OFN99_n91;
   wire FE_OFN98_n90;
   wire FE_OFN97_n89;
   wire FE_OFN96_n88;
   wire FE_OFN95_n87;
   wire FE_OFN94_n86;
   wire FE_OFN93_n85;
   wire FE_OFN92_n84;
   wire FE_OFN91_n83;
   wire FE_OFN90_n82;
   wire FE_OFN89_n81;
   wire FE_OFN88_n80;
   wire FE_OFN87_n79;
   wire FE_OFN86_n78;
   wire FE_OFN85_n77;
   wire FE_OFN84_n76;
   wire FE_OFN83_n75;
   wire FE_OFN82_n74;
   wire FE_OFN81_n73;
   wire FE_OFN80_n72;
   wire FE_OFN79_n71;
   wire FE_OFN78_n70;
   wire FE_OFN77_n69;
   wire FE_OFN76_n68;
   wire FE_OFN75_n67;
   wire FE_OFN74_n66;
   wire FE_OFN73_n65;
   wire FE_OFN72_n64;
   wire FE_OFN71_n63;
   wire FE_OFN70_n62;
   wire FE_OFN69_n61;
   wire FE_OFN68_n60;
   wire FE_OFN67_n59;
   wire FE_OFN66_n58;
   wire FE_OFN65_n57;
   wire FE_OFN64_n56;
   wire FE_OFN63_n55;
   wire FE_OFN62_n54;
   wire FE_OFN61_n53;
   wire FE_OFN60_n52;
   wire FE_OFN59_n51;
   wire FE_OFN58_n50;
   wire FE_OFN57_n49;
   wire FE_OFN56_n48;
   wire FE_OFN55_n47;
   wire FE_OFN54_FE_DBTN0_load;
   wire FE_OFN53_FE_DBTN0_load;
   wire FE_OFN52_FE_DBTN0_load;
   wire FE_OFN51_shift_4;
   wire FE_OFN50_dout;
   wire FE_OFN49_load;
   wire FE_OFN48_load;
   wire FE_OFN47_data_0;
   wire FE_OFN46_data_1;
   wire FE_OFN45_data_2;
   wire FE_OFN44_data_3;
   wire FE_OFN43_data_4;
   wire FE_OFN42_data_5;
   wire FE_OFN41_data_6;
   wire FE_OFN40_data_7;
   wire FE_OFN39_data_8;
   wire FE_OFN38_data_9;
   wire FE_OFN37_data_10;
   wire FE_OFN36_data_11;
   wire FE_OFN35_data_12;
   wire FE_OFN34_data_13;
   wire FE_OFN33_data_14;
   wire FE_OFN32_data_15;
   wire FE_OFN31_data_16;
   wire FE_OFN30_data_17;
   wire FE_OFN29_data_18;
   wire FE_OFN28_data_19;
   wire FE_OFN27_data_20;
   wire FE_OFN26_data_21;
   wire FE_OFN25_data_22;
   wire FE_OFN24_data_23;
   wire FE_OFN23_data_24;
   wire FE_OFN22_data_25;
   wire FE_OFN21_data_26;
   wire FE_OFN20_data_27;
   wire FE_OFN19_data_28;
   wire FE_OFN18_data_29;
   wire FE_OFN17_data_30;
   wire FE_OFN16_data_31;
   wire FE_OFN15_data_32;
   wire FE_OFN14_data_33;
   wire FE_OFN13_data_34;
   wire FE_OFN12_data_35;
   wire FE_OFN11_data_36;
   wire FE_OFN10_data_37;
   wire FE_OFN9_data_38;
   wire FE_OFN8_data_39;
   wire FE_OFN7_data_40;
   wire FE_OFN6_data_41;
   wire FE_OFN5_data_42;
   wire FE_OFN4_data_43;
   wire FE_OFN3_data_44;
   wire FE_OFN2_data_45;
   wire FE_OFN1_data_46;
   wire FE_OFN0_data_47;
   wire FE_DBTN0_load;
   wire N7;
   wire N8;
   wire N9;
   wire N10;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N43;
   wire N44;
   wire N45;
   wire N46;
   wire N47;
   wire N48;
   wire N49;
   wire N50;
   wire N51;
   wire N52;
   wire N53;
   wire N54;
   wire N55;
   wire N56;
   wire net40;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n113;
   wire [47:0] shift;

   // Module instantiations
   BUFFD2 FE_PHC383_FE_OFN56_n48 (
	.I(FE_OFN56_n48),
	.Z(FE_PHN383_FE_OFN56_n48));
   BUFFD0 FE_PHC382_shift_37 (
	.I(shift[37]),
	.Z(FE_PHN382_shift_37));
   BUFFD0 FE_PHC381_shift_33 (
	.I(FE_PHN132_shift_33),
	.Z(FE_PHN381_shift_33));
   BUFFD2 FE_PHC380_n11 (
	.I(n11),
	.Z(FE_PHN380_n11));
   BUFFD0 FE_PHC379_n8 (
	.I(n8),
	.Z(FE_PHN379_n8));
   BUFFD0 FE_PHC378_N22 (
	.I(FE_PHN378_N22),
	.Z(N22));
   BUFFD0 FE_PHC377_N28 (
	.I(N28),
	.Z(FE_PHN377_N28));
   BUFFD1 FE_PHC376_shift_30 (
	.I(FE_PHN376_shift_30),
	.Z(shift[30]));
   BUFFD0 FE_PHC375_shift_43 (
	.I(FE_PHN158_shift_43),
	.Z(FE_PHN375_shift_43));
   BUFFD0 FE_PHC374_shift_17 (
	.I(shift[17]),
	.Z(FE_PHN374_shift_17));
   BUFFD0 FE_PHC373_shift_11 (
	.I(shift[11]),
	.Z(FE_PHN373_shift_11));
   BUFFD0 FE_PHC372_shift_34 (
	.I(shift[34]),
	.Z(FE_PHN372_shift_34));
   BUFFD0 FE_PHC371_shift_44 (
	.I(shift[44]),
	.Z(FE_PHN371_shift_44));
   BUFFD0 FE_PHC370_shift_46 (
	.I(shift[46]),
	.Z(FE_PHN370_shift_46));
   BUFFD0 FE_PHC369_shift_13 (
	.I(shift[13]),
	.Z(FE_PHN369_shift_13));
   BUFFD0 FE_PHC368_presetval_8 (
	.I(presetval[8]),
	.Z(FE_PHN368_presetval_8));
   BUFFD0 FE_PHC367_FE_OFN27_data_20 (
	.I(FE_OFN27_data_20),
	.Z(FE_PHN367_FE_OFN27_data_20));
   BUFFD2 FE_PHC366_FE_OFN3_data_44 (
	.I(FE_OFN3_data_44),
	.Z(FE_PHN366_FE_OFN3_data_44));
   BUFFD0 FE_PHC365_FE_OFN43_data_4 (
	.I(FE_OFN43_data_4),
	.Z(FE_PHN365_FE_OFN43_data_4));
   BUFFD2 FE_PHC364_shift_33 (
	.I(FE_PHN364_shift_33),
	.Z(shift[33]));
   BUFFD0 FE_PHC363_shift_35 (
	.I(shift[35]),
	.Z(FE_PHN363_shift_35));
   BUFFD0 FE_PHC362_FE_OFN32_data_15 (
	.I(FE_OFN32_data_15),
	.Z(FE_PHN362_FE_OFN32_data_15));
   BUFFD2 FE_PHC361_shift_22 (
	.I(FE_PHN361_shift_22),
	.Z(shift[22]));
   BUFFD2 FE_PHC360_shift_41 (
	.I(FE_PHN360_shift_41),
	.Z(shift[41]));
   BUFFD2 FE_PHC359_shift_26 (
	.I(shift[26]),
	.Z(FE_PHN359_shift_26));
   BUFFD0 FE_PHC358_presetval_6 (
	.I(presetval[6]),
	.Z(FE_PHN358_presetval_6));
   BUFFD2 FE_PHC357_shift_28 (
	.I(shift[28]),
	.Z(FE_PHN357_shift_28));
   BUFFD2 FE_PHC356_shift_6 (
	.I(shift[6]),
	.Z(FE_PHN356_shift_6));
   BUFFD2 FE_PHC355_shift_5 (
	.I(FE_PHN355_shift_5),
	.Z(shift[5]));
   BUFFD2 FE_PHC354_shift_18 (
	.I(shift[18]),
	.Z(FE_PHN354_shift_18));
   BUFFD1 FE_PHC353_shift_1 (
	.I(FE_PHN353_shift_1),
	.Z(shift[1]));
   BUFFD2 FE_PHC352_shift_32 (
	.I(shift[32]),
	.Z(FE_PHN352_shift_32));
   BUFFD2 FE_PHC351_shift_39 (
	.I(shift[39]),
	.Z(FE_PHN351_shift_39));
   BUFFD1 FE_PHC350_shift_0 (
	.I(FE_PHN350_shift_0),
	.Z(shift[0]));
   BUFFD1 FE_PHC349_shift_27 (
	.I(shift[27]),
	.Z(FE_PHN349_shift_27));
   BUFFD1 FE_PHC348_shift_15 (
	.I(FE_PHN348_shift_15),
	.Z(shift[15]));
   BUFFD1 FE_PHC347_shift_20 (
	.I(FE_PHN347_shift_20),
	.Z(shift[20]));
   BUFFD1 FE_PHC346_shift_24 (
	.I(shift[24]),
	.Z(FE_PHN346_shift_24));
   BUFFD0 FE_PHC345_shift_7 (
	.I(shift[7]),
	.Z(FE_PHN345_shift_7));
   BUFFD1 FE_PHC344_shift_10 (
	.I(shift[10]),
	.Z(FE_PHN344_shift_10));
   BUFFD1 FE_PHC343_shift_21 (
	.I(shift[21]),
	.Z(FE_PHN343_shift_21));
   BUFFD1 FE_PHC342_shift_12 (
	.I(shift[12]),
	.Z(FE_PHN342_shift_12));
   BUFFD2 FE_PHC341_presetval_39 (
	.I(FE_PHN341_presetval_39),
	.Z(FE_PHN208_presetval_39));
   BUFFD1 FE_PHC340_shift_2 (
	.I(shift[2]),
	.Z(FE_PHN340_shift_2));
   BUFFD0 FE_PHC339_shift_38 (
	.I(FE_PHN339_shift_38),
	.Z(FE_PHN153_shift_38));
   BUFFD0 FE_PHC338_shift_42 (
	.I(FE_PHN164_shift_42),
	.Z(FE_PHN338_shift_42));
   BUFFD2 FE_PHC337_FE_OFN72_n64 (
	.I(FE_PHN234_FE_OFN72_n64),
	.Z(FE_PHN337_FE_OFN72_n64));
   BUFFD0 FE_PHC336_n62 (
	.I(n62),
	.Z(FE_PHN336_n62));
   BUFFD1 FE_PHC335_shift_23 (
	.I(shift[23]),
	.Z(FE_PHN335_shift_23));
   BUFFD0 FE_PHC334_shift_19 (
	.I(FE_PHN334_shift_19),
	.Z(FE_PHN173_shift_19));
   BUFFD2 FE_PHC333_shift_25 (
	.I(FE_PHN333_shift_25),
	.Z(FE_PHN140_shift_25));
   BUFFD0 FE_PHC332_FE_OFN98_n90 (
	.I(FE_PHN238_FE_OFN98_n90),
	.Z(FE_PHN332_FE_OFN98_n90));
   BUFFD0 FE_PHC331_n74 (
	.I(n74),
	.Z(FE_PHN331_n74));
   BUFFD0 FE_PHC330_n66 (
	.I(n66),
	.Z(FE_PHN330_n66));
   BUFFD0 FE_PHC329_FE_OFN110_n96 (
	.I(FE_OFN110_n96),
	.Z(FE_PHN329_FE_OFN110_n96));
   BUFFD0 FE_PHC328_shift_31 (
	.I(FE_PHN145_shift_31),
	.Z(FE_PHN328_shift_31));
   BUFFD0 FE_PHC327_shift_14 (
	.I(FE_PHN142_shift_14),
	.Z(FE_PHN327_shift_14));
   BUFFD0 FE_PHC326_shift_29 (
	.I(FE_PHN326_shift_29),
	.Z(FE_PHN150_shift_29));
   BUFFD0 FE_PHC325_shift_8 (
	.I(FE_PHN325_shift_8),
	.Z(FE_PHN137_shift_8));
   BUFFD0 FE_PHC324_shift_45 (
	.I(FE_PHN144_shift_45),
	.Z(FE_PHN324_shift_45));
   BUFFD0 FE_PHC323_shift_40 (
	.I(FE_PHN141_shift_40),
	.Z(FE_PHN323_shift_40));
   BUFFD0 FE_PHC322_din (
	.I(din),
	.Z(FE_PHN322_din));
   BUFFD0 FE_PHC321_n72 (
	.I(n72),
	.Z(FE_PHN321_n72));
   BUFFD0 FE_PHC320_n68 (
	.I(FE_PHN320_n68),
	.Z(n68));
   BUFFD0 FE_PHC319_presetval_24 (
	.I(FE_PHN178_presetval_24),
	.Z(FE_PHN319_presetval_24));
   BUFFD1 FE_PHC318_presetval_19 (
	.I(FE_PHN291_presetval_19),
	.Z(FE_PHN318_presetval_19));
   DEL005 FE_PHC317_FE_OFN98_n90 (
	.I(FE_PHN238_FE_OFN98_n90),
	.Z(FE_PHN317_FE_OFN98_n90));
   BUFFD2 FE_PHC316_n8 (
	.I(FE_PHN379_n8),
	.Z(FE_PHN316_n8));
   DEL005 FE_PHC315_presetval_19 (
	.I(FE_PHN315_presetval_19),
	.Z(FE_PHN291_presetval_19));
   BUFFD0 FE_PHC314_presetval_12 (
	.I(FE_PHN313_presetval_12),
	.Z(FE_PHN314_presetval_12));
   BUFFD0 FE_PHC313_presetval_12 (
	.I(FE_PHN312_presetval_12),
	.Z(FE_PHN313_presetval_12));
   BUFFD2 FE_PHC312_presetval_12 (
	.I(FE_PHN309_presetval_12),
	.Z(FE_PHN312_presetval_12));
   BUFFD0 FE_PHC311_presetval_16 (
	.I(FE_PHN268_presetval_16),
	.Z(FE_PHN311_presetval_16));
   BUFFD3 FE_PHC310_presetval_12 (
	.I(FE_PHN314_presetval_12),
	.Z(FE_PHN310_presetval_12));
   BUFFD2 FE_PHC309_presetval_12 (
	.I(presetval[12]),
	.Z(FE_PHN309_presetval_12));
   BUFFD0 FE_PHC308_presetval_16 (
	.I(FE_PHN311_presetval_16),
	.Z(FE_PHN308_presetval_16));
   DEL01 FE_PHC307_presetval_18 (
	.I(FE_PHN307_presetval_18),
	.Z(FE_PHN194_presetval_18));
   BUFFD2 FE_PHC306_FE_OFN72_n64 (
	.I(FE_PHN234_FE_OFN72_n64),
	.Z(FE_PHN306_FE_OFN72_n64));
   BUFFD0 FE_PHC305_shift_46 (
	.I(FE_PHN134_shift_46),
	.Z(FE_PHN305_shift_46));
   BUFFD1 FE_PHC304_presetval_12 (
	.I(FE_PHN310_presetval_12),
	.Z(FE_PHN304_presetval_12));
   CKBXD2 FE_PHC303_presetval_16 (
	.I(presetval[16]),
	.Z(FE_PHN303_presetval_16));
   DEL005 FE_PHC302_presetval_18 (
	.I(presetval[18]),
	.Z(FE_PHN302_presetval_18));
   DEL0 FE_PHC301_presetval_14 (
	.I(presetval[14]),
	.Z(FE_PHN301_presetval_14));
   BUFFD2 FE_PHC300_FE_OFN60_n52 (
	.I(FE_OFN60_n52),
	.Z(FE_PHN300_FE_OFN60_n52));
   BUFFD2 FE_PHC299_presetval_12 (
	.I(FE_PHN304_presetval_12),
	.Z(FE_PHN299_presetval_12));
   BUFFD0 FE_PHC298_shift_11 (
	.I(FE_PHN135_shift_11),
	.Z(FE_PHN298_shift_11));
   BUFFD1 FE_PHC297_shift_16 (
	.I(shift[16]),
	.Z(FE_PHN297_shift_16));
   BUFFD0 FE_PHC296_shift_17 (
	.I(FE_PHN139_shift_17),
	.Z(FE_PHN296_shift_17));
   BUFFD0 FE_PHC295_shift_34 (
	.I(FE_PHN131_shift_34),
	.Z(FE_PHN295_shift_34));
   DEL005 FE_PHC294_FE_OFN92_n84 (
	.I(FE_PHN247_FE_OFN92_n84),
	.Z(FE_PHN294_FE_OFN92_n84));
   DEL01 FE_PHC293_FE_OFN88_n80 (
	.I(FE_PHN254_FE_OFN88_n80),
	.Z(FE_PHN293_FE_OFN88_n80));
   BUFFD0 FE_PHC292_FE_OFN98_n90 (
	.I(FE_OFN98_n90),
	.Z(FE_PHN292_FE_OFN98_n90));
   DEL02 FE_PHC291_presetval_19 (
	.I(FE_PHN318_presetval_19),
	.Z(FE_PHN240_presetval_19));
   DEL0 FE_PHC290_presetval_10 (
	.I(presetval[10]),
	.Z(FE_PHN290_presetval_10));
   DEL0 FE_PHC289_presetval_17 (
	.I(presetval[17]),
	.Z(FE_PHN289_presetval_17));
   DEL0 FE_PHC288_presetval_11 (
	.I(presetval[11]),
	.Z(FE_PHN288_presetval_11));
   DEL0 FE_PHC287_presetval_21 (
	.I(FE_PHN287_presetval_21),
	.Z(FE_PHN212_presetval_21));
   DEL02 FE_PHC286_presetval_16 (
	.I(FE_PHN303_presetval_16),
	.Z(FE_PHN286_presetval_16));
   DEL02 FE_PHC285_presetval_18 (
	.I(FE_PHN302_presetval_18),
	.Z(FE_PHN285_presetval_18));
   BUFFD0 FE_PHC284_FE_OFN106_n98 (
	.I(FE_PHN284_FE_OFN106_n98),
	.Z(FE_PHN233_FE_OFN106_n98));
   DEL005 FE_PHC283_FE_OFN64_n56 (
	.I(FE_PHN237_FE_OFN64_n56),
	.Z(FE_PHN283_FE_OFN64_n56));
   BUFFD0 FE_PHC282_FE_OFN56_n48 (
	.I(FE_PHN265_FE_OFN56_n48),
	.Z(FE_PHN282_FE_OFN56_n48));
   DEL0 FE_PHC281_presetval_1 (
	.I(FE_PHN199_presetval_1),
	.Z(FE_PHN281_presetval_1));
   DEL0 FE_PHC280_presetval_5 (
	.I(presetval[5]),
	.Z(FE_PHN280_presetval_5));
   DEL0 FE_PHC279_presetval_13 (
	.I(presetval[13]),
	.Z(FE_PHN279_presetval_13));
   DEL0 FE_PHC278_presetval_7 (
	.I(presetval[7]),
	.Z(FE_PHN278_presetval_7));
   DEL0 FE_PHC277_presetval_9 (
	.I(presetval[9]),
	.Z(FE_PHN277_presetval_9));
   DEL0 FE_PHC276_presetval_15 (
	.I(presetval[15]),
	.Z(FE_PHN276_presetval_15));
   DEL0 FE_PHC275_presetval_0 (
	.I(presetval[0]),
	.Z(FE_PHN275_presetval_0));
   DEL0 FE_PHC274_presetval_8 (
	.I(FE_PHN368_presetval_8),
	.Z(FE_PHN274_presetval_8));
   DEL0 FE_PHC273_presetval_20 (
	.I(presetval[20]),
	.Z(FE_PHN273_presetval_20));
   DEL0 FE_PHC272_n10 (
	.I(n10),
	.Z(FE_PHN272_n10));
   DEL0 FE_PHC271_presetval_2 (
	.I(presetval[2]),
	.Z(FE_PHN271_presetval_2));
   DEL0 FE_PHC270_n12 (
	.I(n12),
	.Z(FE_PHN270_n12));
   DEL0 FE_PHC269_presetval_6 (
	.I(FE_PHN358_presetval_6),
	.Z(FE_PHN269_presetval_6));
   BUFFD0 FE_PHC268_presetval_16 (
	.I(FE_PHN286_presetval_16),
	.Z(FE_PHN268_presetval_16));
   BUFFD0 FE_PHC267_presetval_19 (
	.I(FE_PHN240_presetval_19),
	.Z(FE_PHN267_presetval_19));
   DEL015 FE_PHC266_presetval_15 (
	.I(FE_PHN276_presetval_15),
	.Z(FE_PHN266_presetval_15));
   DEL005 FE_PHC265_FE_OFN56_n48 (
	.I(FE_PHN282_FE_OFN56_n48),
	.Z(FE_OFN56_n48));
   DEL01 FE_PHC264_FE_OFN80_n72 (
	.I(FE_OFN80_n72),
	.Z(FE_PHN264_FE_OFN80_n72));
   DEL005 FE_PHC263_presetval_16 (
	.I(FE_PHN308_presetval_16),
	.Z(FE_PHN263_presetval_16));
   DEL005 FE_PHC262_FE_OFN76_n68 (
	.I(FE_OFN76_n68),
	.Z(FE_PHN262_FE_OFN76_n68));
   DEL0 FE_PHC261_FE_OFN94_n86 (
	.I(FE_OFN94_n86),
	.Z(FE_PHN261_FE_OFN94_n86));
   DEL0 FE_PHC260_FE_OFN68_n60 (
	.I(FE_OFN68_n60),
	.Z(FE_PHN260_FE_OFN68_n60));
   BUFFD0 FE_PHC259_shift_44 (
	.I(FE_PHN160_shift_44),
	.Z(FE_PHN259_shift_44));
   CKBXD2 FE_PHC258_presetval_16 (
	.I(FE_PHN263_presetval_16),
	.Z(FE_PHN258_presetval_16));
   CKBXD2 FE_PHC257_presetval_15 (
	.I(FE_PHN266_presetval_15),
	.Z(FE_PHN257_presetval_15));
   BUFFD2 FE_PHC256_n40 (
	.I(FE_PHN231_n40),
	.Z(FE_PHN256_n40));
   BUFFD0 FE_PHC255_shift_7 (
	.I(FE_PHN168_shift_7),
	.Z(FE_PHN255_shift_7));
   DEL01 FE_PHC254_FE_OFN88_n80 (
	.I(FE_PHN293_FE_OFN88_n80),
	.Z(FE_OFN88_n80));
   BUFFD0 FE_PHC253_n16 (
	.I(n16),
	.Z(FE_PHN253_n16));
   DEL005 FE_PHC252_n42 (
	.I(n42),
	.Z(FE_PHN252_n42));
   DEL005 FE_PHC251_FE_OFN90_n82 (
	.I(FE_PHN251_FE_OFN90_n82),
	.Z(FE_OFN90_n82));
   DEL02 FE_PHC250_presetval_41 (
	.I(presetval[41]),
	.Z(FE_PHN250_presetval_41));
   DEL02 FE_PHC249_presetval_28 (
	.I(presetval[28]),
	.Z(FE_PHN249_presetval_28));
   DEL005 FE_PHC248_FE_OFN82_n74 (
	.I(FE_OFN82_n74),
	.Z(FE_PHN248_FE_OFN82_n74));
   DEL005 FE_PHC247_FE_OFN92_n84 (
	.I(FE_OFN92_n84),
	.Z(FE_PHN247_FE_OFN92_n84));
   DEL015 FE_PHC246_FE_OFN58_n50 (
	.I(FE_PHN246_FE_OFN58_n50),
	.Z(FE_OFN58_n50));
   DEL005 FE_PHC245_FE_OFN74_n66 (
	.I(FE_OFN74_n66),
	.Z(FE_PHN245_FE_OFN74_n66));
   DEL0 FE_PHC244_presetval_34 (
	.I(FE_PHN184_presetval_34),
	.Z(FE_PHN244_presetval_34));
   DEL005 FE_PHC243_FE_OFN70_n62 (
	.I(FE_OFN70_n62),
	.Z(FE_PHN243_FE_OFN70_n62));
   DEL0 FE_PHC242_presetval_32 (
	.I(presetval[32]),
	.Z(FE_PHN242_presetval_32));
   BUFFD0 FE_PHC241_shift_13 (
	.I(FE_PHN172_shift_13),
	.Z(FE_PHN241_shift_13));
   DEL005 FE_PHC240_presetval_19 (
	.I(presetval[19]),
	.Z(FE_PHN315_presetval_19));
   BUFFD0 FE_PHC239_shift_35 (
	.I(shift[35]),
	.Z(FE_PHN239_shift_35));
   DEL005 FE_PHC238_FE_OFN98_n90 (
	.I(FE_PHN292_FE_OFN98_n90),
	.Z(FE_PHN238_FE_OFN98_n90));
   DEL015 FE_PHC237_FE_OFN64_n56 (
	.I(FE_OFN64_n56),
	.Z(FE_PHN237_FE_OFN64_n56));
   DEL005 FE_PHC236_FE_OFN104_n96 (
	.I(FE_PHN236_FE_OFN104_n96),
	.Z(FE_OFN104_n96));
   DEL005 FE_PHC235_n16 (
	.I(FE_PHN253_n16),
	.Z(FE_PHN235_n16));
   DEL005 FE_PHC234_FE_OFN72_n64 (
	.I(FE_OFN72_n64),
	.Z(FE_PHN234_FE_OFN72_n64));
   DEL005 FE_PHC233_FE_OFN106_n98 (
	.I(FE_PHN233_FE_OFN106_n98),
	.Z(FE_OFN106_n98));
   DEL0 FE_PHC232_n14 (
	.I(n14),
	.Z(FE_PHN232_n14));
   DEL005 FE_PHC231_n40 (
	.I(n40),
	.Z(FE_PHN231_n40));
   DEL0 FE_PHC230_presetval_1 (
	.I(presetval[1]),
	.Z(FE_PHN230_presetval_1));
   DEL0 FE_PHC229_n18 (
	.I(n18),
	.Z(FE_PHN229_n18));
   DEL0 FE_PHC228_presetval_11 (
	.I(FE_PHN288_presetval_11),
	.Z(FE_PHN228_presetval_11));
   DEL0 FE_PHC227_presetval_0 (
	.I(FE_PHN198_presetval_0),
	.Z(FE_PHN227_presetval_0));
   DEL0 FE_PHC226_presetval_9 (
	.I(FE_PHN197_presetval_9),
	.Z(FE_PHN226_presetval_9));
   DEL015 FE_PHC225_FE_OFN102_n94 (
	.I(FE_OFN102_n94),
	.Z(FE_PHN225_FE_OFN102_n94));
   DEL0 FE_PHC224_presetval_13 (
	.I(FE_PHN201_presetval_13),
	.Z(FE_PHN224_presetval_13));
   DEL0 FE_PHC223_presetval_14 (
	.I(FE_PHN202_presetval_14),
	.Z(FE_PHN223_presetval_14));
   DEL015 FE_PHC222_FE_OFN66_n58 (
	.I(FE_OFN66_n58),
	.Z(FE_PHN222_FE_OFN66_n58));
   DEL0 FE_PHC221_FE_OFN84_n76 (
	.I(FE_PHN221_FE_OFN84_n76),
	.Z(FE_OFN84_n76));
   DEL0 FE_PHC220_FE_OFN78_n70 (
	.I(FE_OFN78_n70),
	.Z(FE_PHN220_FE_OFN78_n70));
   DEL0 FE_PHC219_presetval_10 (
	.I(FE_PHN290_presetval_10),
	.Z(FE_PHN219_presetval_10));
   DEL0 FE_PHC218_FE_OFN100_n92 (
	.I(FE_OFN100_n92),
	.Z(FE_PHN218_FE_OFN100_n92));
   DEL0 FE_PHC217_FE_OFN96_n88 (
	.I(FE_OFN96_n88),
	.Z(FE_PHN217_FE_OFN96_n88));
   DEL0 FE_PHC216_presetval_17 (
	.I(FE_PHN289_presetval_17),
	.Z(FE_PHN216_presetval_17));
   DEL0 FE_PHC215_presetval_23 (
	.I(presetval[23]),
	.Z(FE_PHN215_presetval_23));
   DEL0 FE_PHC214_FE_OFN86_n78 (
	.I(FE_PHN214_FE_OFN86_n78),
	.Z(FE_OFN86_n78));
   DEL0 FE_PHC213_FE_OFN62_n54 (
	.I(FE_PHN213_FE_OFN62_n54),
	.Z(FE_OFN62_n54));
   DEL0 FE_PHC212_presetval_21 (
	.I(presetval[21]),
	.Z(FE_PHN287_presetval_21));
   DEL0 FE_PHC211_presetval_35 (
	.I(presetval[35]),
	.Z(FE_PHN211_presetval_35));
   DEL0 FE_PHC210_presetval_31 (
	.I(presetval[31]),
	.Z(FE_PHN210_presetval_31));
   DEL0 FE_PHC209_presetval_29 (
	.I(presetval[29]),
	.Z(FE_PHN209_presetval_29));
   DEL0 FE_PHC208_presetval_39 (
	.I(presetval[39]),
	.Z(FE_PHN341_presetval_39));
   DEL0 FE_PHC207_presetval_24 (
	.I(presetval[24]),
	.Z(FE_PHN207_presetval_24));
   DEL0 FE_PHC206_presetval_40 (
	.I(presetval[40]),
	.Z(FE_PHN206_presetval_40));
   BUFFD2 FE_PHC205_presetval_17 (
	.I(FE_PHN216_presetval_17),
	.Z(FE_PHN205_presetval_17));
   BUFFD2 FE_PHC204_presetval_11 (
	.I(FE_PHN228_presetval_11),
	.Z(FE_PHN204_presetval_11));
   BUFFD2 FE_PHC203_presetval_10 (
	.I(FE_PHN219_presetval_10),
	.Z(FE_PHN203_presetval_10));
   BUFFD2 FE_PHC202_presetval_14 (
	.I(FE_PHN301_presetval_14),
	.Z(FE_PHN202_presetval_14));
   BUFFD2 FE_PHC201_presetval_13 (
	.I(FE_PHN279_presetval_13),
	.Z(FE_PHN201_presetval_13));
   CKBXD2 FE_PHC200_presetval_6 (
	.I(FE_PHN269_presetval_6),
	.Z(FE_PHN200_presetval_6));
   BUFFD2 FE_PHC199_presetval_1 (
	.I(FE_PHN230_presetval_1),
	.Z(FE_PHN199_presetval_1));
   BUFFD2 FE_PHC198_presetval_0 (
	.I(FE_PHN275_presetval_0),
	.Z(FE_PHN198_presetval_0));
   BUFFD2 FE_PHC197_presetval_9 (
	.I(FE_PHN277_presetval_9),
	.Z(FE_PHN197_presetval_9));
   BUFFD2 FE_PHC196_presetval_7 (
	.I(FE_PHN278_presetval_7),
	.Z(FE_PHN196_presetval_7));
   BUFFD2 FE_PHC195_presetval_5 (
	.I(FE_PHN280_presetval_5),
	.Z(FE_PHN195_presetval_5));
   DEL005 FE_PHC194_presetval_18 (
	.I(FE_PHN285_presetval_18),
	.Z(FE_PHN307_presetval_18));
   DEL015 FE_PHC193_presetval_2 (
	.I(FE_PHN271_presetval_2),
	.Z(FE_PHN193_presetval_2));
   DEL02 FE_PHC192_presetval_8 (
	.I(FE_PHN274_presetval_8),
	.Z(FE_PHN192_presetval_8));
   DEL02 FE_PHC191_presetval_12 (
	.I(FE_PHN299_presetval_12),
	.Z(FE_PHN191_presetval_12));
   DEL02 FE_PHC190_presetval_20 (
	.I(FE_PHN273_presetval_20),
	.Z(FE_PHN190_presetval_20));
   DEL015 FE_PHC189_shift_3 (
	.I(shift[3]),
	.Z(FE_PHN189_shift_3));
   BUFFD2 FE_PHC188_load (
	.I(load),
	.Z(FE_PHN188_load));
   BUFFD2 FE_PHC187_presetval_41 (
	.I(FE_PHN250_presetval_41),
	.Z(FE_PHN187_presetval_41));
   BUFFD2 FE_PHC186_presetval_29 (
	.I(FE_PHN209_presetval_29),
	.Z(FE_PHN186_presetval_29));
   BUFFD2 FE_PHC185_presetval_28 (
	.I(FE_PHN249_presetval_28),
	.Z(FE_PHN185_presetval_28));
   CKBXD2 FE_PHC184_presetval_34 (
	.I(presetval[34]),
	.Z(FE_PHN184_presetval_34));
   BUFFD2 FE_PHC183_presetval_32 (
	.I(FE_PHN242_presetval_32),
	.Z(FE_PHN183_presetval_32));
   BUFFD2 FE_PHC182_presetval_40 (
	.I(FE_PHN206_presetval_40),
	.Z(FE_PHN182_presetval_40));
   BUFFD2 FE_PHC181_presetval_31 (
	.I(FE_PHN210_presetval_31),
	.Z(FE_PHN181_presetval_31));
   BUFFD2 FE_PHC180_presetval_35 (
	.I(FE_PHN211_presetval_35),
	.Z(FE_PHN180_presetval_35));
   BUFFD1 FE_PHC179_presetval_39 (
	.I(FE_PHN208_presetval_39),
	.Z(FE_PHN179_presetval_39));
   DEL01 FE_PHC178_presetval_24 (
	.I(FE_PHN207_presetval_24),
	.Z(FE_PHN178_presetval_24));
   BUFFD0 FE_PHC177_FE_OFN51_shift_4 (
	.I(FE_OFN51_shift_4),
	.Z(FE_PHN177_FE_OFN51_shift_4));
   DEL02 FE_PHC176_presetval_4 (
	.I(presetval[4]),
	.Z(FE_PHN176_presetval_4));
   BUFFD0 FE_PHC175_shift_35 (
	.I(FE_PHN239_shift_35),
	.Z(FE_PHN175_shift_35));
   DEL0 FE_PHC174_shift_47 (
	.I(shift[47]),
	.Z(FE_PHN174_shift_47));
   DEL01 FE_PHC173_shift_19 (
	.I(shift[19]),
	.Z(FE_PHN334_shift_19));
   DEL005 FE_PHC172_shift_13 (
	.I(shift[13]),
	.Z(FE_PHN172_shift_13));
   DEL0 FE_PHC171_shift_9 (
	.I(shift[9]),
	.Z(FE_PHN171_shift_9));
   DEL01 FE_PHC170_shift_5 (
	.I(shift[5]),
	.Z(FE_PHN170_shift_5));
   DEL005 FE_PHC169_shift_30 (
	.I(shift[30]),
	.Z(FE_PHN169_shift_30));
   DEL005 FE_PHC168_shift_7 (
	.I(shift[7]),
	.Z(FE_PHN168_shift_7));
   DEL01 FE_PHC167_shift_39 (
	.I(FE_PHN351_shift_39),
	.Z(FE_PHN167_shift_39));
   DEL015 FE_PHC166_shift_26 (
	.I(FE_PHN359_shift_26),
	.Z(FE_PHN166_shift_26));
   DEL01 FE_PHC165_shift_10 (
	.I(FE_PHN344_shift_10),
	.Z(FE_PHN165_shift_10));
   DEL01 FE_PHC164_shift_42 (
	.I(shift[42]),
	.Z(FE_PHN164_shift_42));
   DEL005 FE_PHC163_shift_23 (
	.I(FE_PHN335_shift_23),
	.Z(FE_PHN163_shift_23));
   DEL015 FE_PHC162_shift_36 (
	.I(shift[36]),
	.Z(FE_PHN162_shift_36));
   DEL01 FE_PHC161_shift_32 (
	.I(FE_PHN352_shift_32),
	.Z(FE_PHN161_shift_32));
   DEL005 FE_PHC160_shift_44 (
	.I(shift[44]),
	.Z(FE_PHN160_shift_44));
   DEL01 FE_PHC159_shift_18 (
	.I(FE_PHN354_shift_18),
	.Z(FE_PHN159_shift_18));
   DEL01 FE_PHC158_shift_43 (
	.I(shift[43]),
	.Z(FE_PHN158_shift_43));
   DEL015 FE_PHC157_shift_41 (
	.I(shift[41]),
	.Z(FE_PHN157_shift_41));
   DEL01 FE_PHC156_shift_22 (
	.I(shift[22]),
	.Z(FE_PHN156_shift_22));
   DEL01 FE_PHC155_shift_0 (
	.I(shift[0]),
	.Z(FE_PHN155_shift_0));
   DEL01 FE_PHC154_shift_12 (
	.I(FE_PHN342_shift_12),
	.Z(FE_PHN154_shift_12));
   DEL005 FE_PHC153_shift_38 (
	.I(shift[38]),
	.Z(FE_PHN339_shift_38));
   DEL005 FE_PHC152_shift_24 (
	.I(FE_PHN346_shift_24),
	.Z(FE_PHN152_shift_24));
   DEL005 FE_PHC151_shift_27 (
	.I(FE_PHN349_shift_27),
	.Z(FE_PHN151_shift_27));
   DEL005 FE_PHC150_shift_29 (
	.I(shift[29]),
	.Z(FE_PHN326_shift_29));
   DEL005 FE_PHC149_shift_20 (
	.I(shift[20]),
	.Z(FE_PHN149_shift_20));
   DEL015 FE_PHC148_shift_37 (
	.I(shift[37]),
	.Z(FE_PHN148_shift_37));
   DEL005 FE_PHC147_shift_2 (
	.I(FE_PHN340_shift_2),
	.Z(FE_PHN147_shift_2));
   DEL005 FE_PHC146_shift_15 (
	.I(shift[15]),
	.Z(FE_PHN146_shift_15));
   DEL005 FE_PHC145_shift_31 (
	.I(shift[31]),
	.Z(FE_PHN145_shift_31));
   DEL005 FE_PHC144_shift_45 (
	.I(shift[45]),
	.Z(FE_PHN144_shift_45));
   DEL01 FE_PHC143_shift_28 (
	.I(FE_PHN357_shift_28),
	.Z(FE_PHN143_shift_28));
   DEL005 FE_PHC142_shift_14 (
	.I(shift[14]),
	.Z(FE_PHN142_shift_14));
   DEL005 FE_PHC141_shift_40 (
	.I(shift[40]),
	.Z(FE_PHN141_shift_40));
   DEL005 FE_PHC140_shift_25 (
	.I(shift[25]),
	.Z(FE_PHN333_shift_25));
   DEL005 FE_PHC139_shift_17 (
	.I(shift[17]),
	.Z(FE_PHN139_shift_17));
   DEL01 FE_PHC138_shift_1 (
	.I(shift[1]),
	.Z(FE_PHN138_shift_1));
   DEL005 FE_PHC137_shift_8 (
	.I(shift[8]),
	.Z(FE_PHN325_shift_8));
   DEL005 FE_PHC136_shift_16 (
	.I(FE_PHN297_shift_16),
	.Z(FE_PHN136_shift_16));
   DEL005 FE_PHC135_shift_11 (
	.I(shift[11]),
	.Z(FE_PHN135_shift_11));
   DEL005 FE_PHC134_shift_46 (
	.I(shift[46]),
	.Z(FE_PHN134_shift_46));
   DEL01 FE_PHC133_shift_6 (
	.I(FE_PHN356_shift_6),
	.Z(FE_PHN133_shift_6));
   DEL01 FE_PHC132_shift_33 (
	.I(shift[33]),
	.Z(FE_PHN132_shift_33));
   DEL005 FE_PHC131_shift_34 (
	.I(shift[34]),
	.Z(FE_PHN131_shift_34));
   DEL005 FE_PHC130_shift_21 (
	.I(FE_PHN343_shift_21),
	.Z(FE_PHN130_shift_21));
   DEL0 FE_PHC129_presetval_30 (
	.I(presetval[30]),
	.Z(FE_PHN129_presetval_30));
   DEL0 FE_PHC128_presetval_37 (
	.I(presetval[37]),
	.Z(FE_PHN128_presetval_37));
   DEL0 FE_PHC127_presetval_38 (
	.I(presetval[38]),
	.Z(FE_PHN127_presetval_38));
   DEL0 FE_PHC126_presetval_27 (
	.I(presetval[27]),
	.Z(FE_PHN126_presetval_27));
   DEL0 FE_PHC125_presetval_43 (
	.I(presetval[43]),
	.Z(FE_PHN125_presetval_43));
   DEL0 FE_PHC124_presetval_25 (
	.I(presetval[25]),
	.Z(FE_PHN124_presetval_25));
   DEL0 FE_PHC123_presetval_36 (
	.I(presetval[36]),
	.Z(FE_PHN123_presetval_36));
   DEL0 FE_PHC122_presetval_42 (
	.I(presetval[42]),
	.Z(FE_PHN122_presetval_42));
   DEL0 FE_PHC121_presetval_44 (
	.I(presetval[44]),
	.Z(FE_PHN121_presetval_44));
   DEL0 FE_PHC120_presetval_26 (
	.I(presetval[26]),
	.Z(FE_PHN120_presetval_26));
   DEL0 FE_PHC119_presetval_46 (
	.I(presetval[46]),
	.Z(FE_PHN119_presetval_46));
   DEL0 FE_PHC118_presetval_33 (
	.I(presetval[33]),
	.Z(FE_PHN118_presetval_33));
   DEL0 FE_PHC117_presetval_47 (
	.I(presetval[47]),
	.Z(FE_PHN117_presetval_47));
   DEL0 FE_PHC116_presetval_22 (
	.I(presetval[22]),
	.Z(FE_PHN116_presetval_22));
   DEL0 FE_PHC115_presetval_45 (
	.I(presetval[45]),
	.Z(FE_PHN115_presetval_45));
   DEL0 FE_PHC114_presetval_3 (
	.I(presetval[3]),
	.Z(FE_PHN114_presetval_3));
   BUFFD0 FE_OFC112_n64 (
	.I(n64),
	.Z(FE_OFN112_n64));
   BUFFD0 FE_OFC111_n83 (
	.I(n83),
	.Z(FE_OFN111_n83));
   BUFFD0 FE_OFC110_n96 (
	.I(n96),
	.Z(FE_OFN110_n96));
   BUFFD0 FE_OFC109_n113 (
	.I(n113),
	.Z(FE_OFN109_n113));
   BUFFD0 FE_OFC108_n63 (
	.I(n63),
	.Z(FE_OFN108_n63));
   BUFFD2 FE_OFC108_FE_OFN48_load (
	.I(FE_OFN48_load),
	.Z(FE_OFN108_FE_OFN48_load));
   CKNXD8 CTS_ccl_INV_clk_G1_L3_2 (
	.I(CTS_23),
	.ZN(CTS_22));
   CKNXD4 CTS_ccl_INV_clk_G1_L2_2 (
	.I(CTS_24),
	.ZN(CTS_23));
   CKNXD8 CTS_ccl_INV_clk_G1_L3_1 (
	.I(CTS_20),
	.ZN(CTS_19));
   CKNXD4 CTS_ccl_INV_clk_G1_L2_1 (
	.I(CTS_21),
	.ZN(CTS_20));
   BUFFD2 FE_OFC107_n113 (
	.I(FE_OFN109_n113),
	.Z(FE_OFN107_n113));
   DEL005 FE_OFC106_n98 (
	.I(n98),
	.Z(FE_PHN284_FE_OFN106_n98));
   BUFFD2 FE_OFC105_n97 (
	.I(n97),
	.Z(FE_OFN105_n97));
   BUFFD0 FE_OFC104_n96 (
	.I(FE_PHN329_FE_OFN110_n96),
	.Z(FE_PHN236_FE_OFN104_n96));
   BUFFD2 FE_OFC103_n95 (
	.I(n95),
	.Z(FE_OFN103_n95));
   BUFFD2 FE_OFC102_n94 (
	.I(n94),
	.Z(FE_OFN102_n94));
   BUFFD2 FE_OFC101_n93 (
	.I(n93),
	.Z(FE_OFN101_n93));
   BUFFD2 FE_OFC100_n92 (
	.I(n92),
	.Z(FE_OFN100_n92));
   BUFFD2 FE_OFC99_n91 (
	.I(n91),
	.Z(FE_OFN99_n91));
   BUFFD2 FE_OFC98_n90 (
	.I(n90),
	.Z(FE_OFN98_n90));
   BUFFD2 FE_OFC97_n89 (
	.I(n89),
	.Z(FE_OFN97_n89));
   BUFFD2 FE_OFC96_n88 (
	.I(n88),
	.Z(FE_OFN96_n88));
   BUFFD2 FE_OFC95_n87 (
	.I(n87),
	.Z(FE_OFN95_n87));
   BUFFD2 FE_OFC94_n86 (
	.I(n86),
	.Z(FE_OFN94_n86));
   BUFFD2 FE_OFC93_n85 (
	.I(n85),
	.Z(FE_OFN93_n85));
   BUFFD2 FE_OFC92_n84 (
	.I(n84),
	.Z(FE_OFN92_n84));
   BUFFD2 FE_OFC91_n83 (
	.I(FE_OFN111_n83),
	.Z(FE_OFN91_n83));
   BUFFD2 FE_OFC90_n82 (
	.I(n82),
	.Z(FE_PHN251_FE_OFN90_n82));
   BUFFD2 FE_OFC89_n81 (
	.I(n81),
	.Z(FE_OFN89_n81));
   DEL005 FE_OFC88_n80 (
	.I(n80),
	.Z(FE_PHN254_FE_OFN88_n80));
   BUFFD2 FE_OFC87_n79 (
	.I(n79),
	.Z(FE_OFN87_n79));
   BUFFD2 FE_OFC86_n78 (
	.I(n78),
	.Z(FE_PHN214_FE_OFN86_n78));
   BUFFD2 FE_OFC85_n77 (
	.I(n77),
	.Z(FE_OFN85_n77));
   BUFFD2 FE_OFC84_n76 (
	.I(n76),
	.Z(FE_PHN221_FE_OFN84_n76));
   BUFFD2 FE_OFC83_n75 (
	.I(n75),
	.Z(FE_OFN83_n75));
   BUFFD0 FE_OFC82_n74 (
	.I(FE_PHN331_n74),
	.Z(FE_OFN82_n74));
   BUFFD2 FE_OFC81_n73 (
	.I(n73),
	.Z(FE_OFN81_n73));
   BUFFD0 FE_OFC80_n72 (
	.I(FE_PHN321_n72),
	.Z(FE_OFN80_n72));
   BUFFD2 FE_OFC79_n71 (
	.I(n71),
	.Z(FE_OFN79_n71));
   BUFFD2 FE_OFC78_n70 (
	.I(n70),
	.Z(FE_OFN78_n70));
   BUFFD2 FE_OFC77_n69 (
	.I(n69),
	.Z(FE_OFN77_n69));
   BUFFD0 FE_OFC76_n68 (
	.I(n68),
	.Z(FE_OFN76_n68));
   BUFFD2 FE_OFC75_n67 (
	.I(n67),
	.Z(FE_OFN75_n67));
   BUFFD0 FE_OFC74_n66 (
	.I(FE_PHN330_n66),
	.Z(FE_OFN74_n66));
   BUFFD2 FE_OFC73_n65 (
	.I(n65),
	.Z(FE_OFN73_n65));
   BUFFD0 FE_OFC72_n64 (
	.I(FE_OFN112_n64),
	.Z(FE_OFN72_n64));
   BUFFD2 FE_OFC71_n63 (
	.I(FE_OFN108_n63),
	.Z(FE_OFN71_n63));
   BUFFD0 FE_OFC70_n62 (
	.I(FE_PHN336_n62),
	.Z(FE_OFN70_n62));
   BUFFD2 FE_OFC69_n61 (
	.I(n61),
	.Z(FE_OFN69_n61));
   BUFFD2 FE_OFC68_n60 (
	.I(n60),
	.Z(FE_OFN68_n60));
   BUFFD2 FE_OFC67_n59 (
	.I(n59),
	.Z(FE_OFN67_n59));
   BUFFD2 FE_OFC66_n58 (
	.I(n58),
	.Z(FE_OFN66_n58));
   BUFFD2 FE_OFC65_n57 (
	.I(n57),
	.Z(FE_OFN65_n57));
   BUFFD2 FE_OFC64_n56 (
	.I(n56),
	.Z(FE_OFN64_n56));
   BUFFD2 FE_OFC63_n55 (
	.I(n55),
	.Z(FE_OFN63_n55));
   BUFFD2 FE_OFC62_n54 (
	.I(n54),
	.Z(FE_PHN213_FE_OFN62_n54));
   BUFFD2 FE_OFC61_n53 (
	.I(n53),
	.Z(FE_OFN61_n53));
   DEL005 FE_OFC60_n52 (
	.I(n52),
	.Z(FE_OFN60_n52));
   BUFFD2 FE_OFC59_n51 (
	.I(n51),
	.Z(FE_OFN59_n51));
   BUFFD2 FE_OFC58_n50 (
	.I(n50),
	.Z(FE_PHN246_FE_OFN58_n50));
   BUFFD2 FE_OFC57_n49 (
	.I(n49),
	.Z(FE_OFN57_n49));
   DEL005 FE_OFC56_n48 (
	.I(n48),
	.Z(FE_PHN265_FE_OFN56_n48));
   BUFFD2 FE_OFC55_n47 (
	.I(n47),
	.Z(FE_OFN55_n47));
   BUFFD6 FE_OFC54_FE_DBTN0_load (
	.I(FE_OFN53_FE_DBTN0_load),
	.Z(FE_OFN54_FE_DBTN0_load));
   BUFFD3 FE_OFC53_FE_DBTN0_load (
	.I(FE_OFN52_FE_DBTN0_load),
	.Z(FE_OFN53_FE_DBTN0_load));
   BUFFD6 FE_OFC52_FE_DBTN0_load (
	.I(FE_DBTN0_load),
	.Z(FE_OFN52_FE_DBTN0_load));
   BUFFD2 FE_OFC51_shift_4 (
	.I(shift[4]),
	.Z(FE_OFN51_shift_4));
   BUFFD6 FE_OFC50_dout (
	.I(FE_OFN50_dout),
	.Z(dout));
   BUFFD3 FE_OFC49_load (
	.I(FE_OFN48_load),
	.Z(FE_OFN49_load));
   BUFFD12 FE_OFC48_load (
	.I(FE_PHN188_load),
	.Z(FE_OFN48_load));
   BUFFD6 FE_OFC47_data_0 (
	.I(FE_OFN47_data_0),
	.Z(data[0]));
   BUFFD6 FE_OFC46_data_1 (
	.I(FE_OFN46_data_1),
	.Z(data[1]));
   BUFFD6 FE_OFC45_data_2 (
	.I(FE_OFN45_data_2),
	.Z(data[2]));
   BUFFD6 FE_OFC44_data_3 (
	.I(FE_OFN44_data_3),
	.Z(data[3]));
   BUFFD6 FE_OFC43_data_4 (
	.I(FE_OFN43_data_4),
	.Z(data[4]));
   BUFFD6 FE_OFC42_data_5 (
	.I(FE_OFN42_data_5),
	.Z(data[5]));
   BUFFD6 FE_OFC41_data_6 (
	.I(FE_OFN41_data_6),
	.Z(data[6]));
   BUFFD6 FE_OFC40_data_7 (
	.I(FE_OFN40_data_7),
	.Z(data[7]));
   BUFFD6 FE_OFC39_data_8 (
	.I(FE_OFN39_data_8),
	.Z(data[8]));
   BUFFD6 FE_OFC38_data_9 (
	.I(FE_OFN38_data_9),
	.Z(data[9]));
   BUFFD6 FE_OFC37_data_10 (
	.I(FE_OFN37_data_10),
	.Z(data[10]));
   BUFFD6 FE_OFC36_data_11 (
	.I(FE_OFN36_data_11),
	.Z(data[11]));
   BUFFD6 FE_OFC35_data_12 (
	.I(FE_OFN35_data_12),
	.Z(data[12]));
   BUFFD6 FE_OFC34_data_13 (
	.I(FE_OFN34_data_13),
	.Z(data[13]));
   BUFFD6 FE_OFC33_data_14 (
	.I(FE_OFN33_data_14),
	.Z(data[14]));
   BUFFD6 FE_OFC32_data_15 (
	.I(FE_OFN32_data_15),
	.Z(data[15]));
   BUFFD6 FE_OFC31_data_16 (
	.I(FE_OFN31_data_16),
	.Z(data[16]));
   BUFFD6 FE_OFC30_data_17 (
	.I(FE_OFN30_data_17),
	.Z(data[17]));
   BUFFD6 FE_OFC29_data_18 (
	.I(FE_OFN29_data_18),
	.Z(data[18]));
   BUFFD6 FE_OFC28_data_19 (
	.I(FE_OFN28_data_19),
	.Z(data[19]));
   BUFFD6 FE_OFC27_data_20 (
	.I(FE_OFN27_data_20),
	.Z(data[20]));
   BUFFD6 FE_OFC26_data_21 (
	.I(FE_OFN26_data_21),
	.Z(data[21]));
   BUFFD6 FE_OFC25_data_22 (
	.I(FE_OFN25_data_22),
	.Z(data[22]));
   BUFFD6 FE_OFC24_data_23 (
	.I(FE_OFN24_data_23),
	.Z(data[23]));
   BUFFD6 FE_OFC23_data_24 (
	.I(FE_OFN23_data_24),
	.Z(data[24]));
   BUFFD6 FE_OFC22_data_25 (
	.I(FE_OFN22_data_25),
	.Z(data[25]));
   BUFFD6 FE_OFC21_data_26 (
	.I(FE_OFN21_data_26),
	.Z(data[26]));
   BUFFD6 FE_OFC20_data_27 (
	.I(FE_OFN20_data_27),
	.Z(data[27]));
   BUFFD6 FE_OFC19_data_28 (
	.I(FE_OFN19_data_28),
	.Z(data[28]));
   BUFFD6 FE_OFC18_data_29 (
	.I(FE_OFN18_data_29),
	.Z(data[29]));
   BUFFD6 FE_OFC17_data_30 (
	.I(FE_OFN17_data_30),
	.Z(data[30]));
   BUFFD6 FE_OFC16_data_31 (
	.I(FE_OFN16_data_31),
	.Z(data[31]));
   BUFFD6 FE_OFC15_data_32 (
	.I(FE_OFN15_data_32),
	.Z(data[32]));
   BUFFD6 FE_OFC14_data_33 (
	.I(FE_OFN14_data_33),
	.Z(data[33]));
   BUFFD6 FE_OFC13_data_34 (
	.I(FE_OFN13_data_34),
	.Z(data[34]));
   BUFFD6 FE_OFC12_data_35 (
	.I(FE_OFN12_data_35),
	.Z(data[35]));
   BUFFD6 FE_OFC11_data_36 (
	.I(FE_OFN11_data_36),
	.Z(data[36]));
   BUFFD6 FE_OFC10_data_37 (
	.I(FE_OFN10_data_37),
	.Z(data[37]));
   BUFFD6 FE_OFC9_data_38 (
	.I(FE_OFN9_data_38),
	.Z(data[38]));
   BUFFD6 FE_OFC8_data_39 (
	.I(FE_OFN8_data_39),
	.Z(data[39]));
   BUFFD6 FE_OFC7_data_40 (
	.I(FE_OFN7_data_40),
	.Z(data[40]));
   BUFFD6 FE_OFC6_data_41 (
	.I(FE_OFN6_data_41),
	.Z(data[41]));
   BUFFD6 FE_OFC5_data_42 (
	.I(FE_OFN5_data_42),
	.Z(data[42]));
   BUFFD6 FE_OFC4_data_43 (
	.I(FE_OFN4_data_43),
	.Z(data[43]));
   BUFFD6 FE_OFC3_data_44 (
	.I(FE_OFN3_data_44),
	.Z(data[44]));
   BUFFD6 FE_OFC2_data_45 (
	.I(FE_OFN2_data_45),
	.Z(data[45]));
   BUFFD6 FE_OFC1_data_46 (
	.I(FE_OFN1_data_46),
	.Z(data[46]));
   BUFFD6 FE_OFC0_data_47 (
	.I(FE_OFN0_data_47),
	.Z(data[47]));
   CKND1 FE_DBTC0_load (
	.CLK(FE_OFN108_FE_OFN48_load),
	.CN(FE_DBTN0_load));
   SNPS_CLOCK_GATE_HIGH_SPI_slave_48bit_0 clk_gate_shift_reg (
	.CLK(clk),
	.EN(N7),
	.ENCLK(CTS_24),
	.TE(net40));
   SNPS_CLOCK_GATE_HIGH_SPI_slave_48bit_1 clk_gate_data_reg (
	.CLK(clk),
	.EN(N8),
	.ENCLK(CTS_21),
	.TE(net40));
   DFCSNQD1 shift_reg_0_ (
	.CDN(n4),
	.CP(CTS_22),
	.D(N9),
	.Q(FE_PHN350_shift_0),
	.SDN(n3));
   DFCSNQD1 shift_reg_1_ (
	.CDN(n6),
	.CP(CTS_22),
	.D(N10),
	.Q(FE_PHN353_shift_1),
	.SDN(n5));
   DFCSNQD1 shift_reg_2_ (
	.CDN(FE_PHN316_n8),
	.CP(CTS_22),
	.D(N11),
	.Q(shift[2]),
	.SDN(n7));
   DFCSNQD1 shift_reg_3_ (
	.CDN(FE_PHN272_n10),
	.CP(CTS_22),
	.D(N12),
	.Q(shift[3]),
	.SDN(n9));
   DFCSNQD1 shift_reg_4_ (
	.CDN(FE_PHN270_n12),
	.CP(CTS_22),
	.D(N13),
	.Q(shift[4]),
	.SDN(FE_PHN380_n11));
   DFCSNQD1 shift_reg_5_ (
	.CDN(FE_PHN232_n14),
	.CP(CTS_22),
	.D(N14),
	.Q(FE_PHN355_shift_5),
	.SDN(n13));
   DFCSNQD1 shift_reg_6_ (
	.CDN(FE_PHN235_n16),
	.CP(CTS_22),
	.D(N15),
	.Q(shift[6]),
	.SDN(n15));
   DFCSNQD1 shift_reg_7_ (
	.CDN(FE_PHN229_n18),
	.CP(CTS_22),
	.D(N16),
	.Q(shift[7]),
	.SDN(n17));
   DFCSNQD1 shift_reg_8_ (
	.CDN(n20),
	.CP(CTS_22),
	.D(N17),
	.Q(shift[8]),
	.SDN(n19));
   DFCSNQD1 shift_reg_9_ (
	.CDN(n22),
	.CP(CTS_22),
	.D(N18),
	.Q(shift[9]),
	.SDN(n21));
   DFCSNQD1 shift_reg_10_ (
	.CDN(n24),
	.CP(CTS_22),
	.D(N19),
	.Q(shift[10]),
	.SDN(n23));
   DFCSNQD1 shift_reg_11_ (
	.CDN(n26),
	.CP(CTS_22),
	.D(N20),
	.Q(shift[11]),
	.SDN(n25));
   DFCSNQD1 shift_reg_12_ (
	.CDN(n28),
	.CP(CTS_22),
	.D(N21),
	.Q(shift[12]),
	.SDN(n27));
   DFCSNQD1 shift_reg_13_ (
	.CDN(n30),
	.CP(CTS_22),
	.D(N22),
	.Q(shift[13]),
	.SDN(n29));
   DFCSNQD1 shift_reg_14_ (
	.CDN(n32),
	.CP(CTS_22),
	.D(N23),
	.Q(shift[14]),
	.SDN(n31));
   DFCSNQD1 shift_reg_15_ (
	.CDN(n34),
	.CP(CTS_22),
	.D(N24),
	.Q(FE_PHN348_shift_15),
	.SDN(n33));
   DFCSNQD1 shift_reg_16_ (
	.CDN(n36),
	.CP(CTS_22),
	.D(N25),
	.Q(shift[16]),
	.SDN(n35));
   DFCSNQD1 shift_reg_17_ (
	.CDN(n38),
	.CP(CTS_22),
	.D(N26),
	.Q(shift[17]),
	.SDN(n37));
   DFCSNQD1 shift_reg_18_ (
	.CDN(FE_PHN231_n40),
	.CP(CTS_22),
	.D(N27),
	.Q(shift[18]),
	.SDN(n39));
   DFCSNQD1 shift_reg_19_ (
	.CDN(FE_PHN252_n42),
	.CP(CTS_22),
	.D(FE_PHN377_N28),
	.Q(shift[19]),
	.SDN(n41));
   DFCSNQD1 shift_reg_20_ (
	.CDN(n44),
	.CP(CTS_22),
	.D(N29),
	.Q(FE_PHN347_shift_20),
	.SDN(n43));
   DFCSNQD1 shift_reg_21_ (
	.CDN(n46),
	.CP(CTS_22),
	.D(N30),
	.Q(shift[21]),
	.SDN(n45));
   DFCSNQD1 shift_reg_22_ (
	.CDN(FE_OFN56_n48),
	.CP(CTS_22),
	.D(N31),
	.Q(FE_PHN361_shift_22),
	.SDN(FE_OFN55_n47));
   DFCSNQD1 shift_reg_23_ (
	.CDN(FE_OFN58_n50),
	.CP(CTS_22),
	.D(N32),
	.Q(shift[23]),
	.SDN(FE_OFN57_n49));
   DFCSNQD1 shift_reg_24_ (
	.CDN(FE_OFN60_n52),
	.CP(CTS_22),
	.D(N33),
	.Q(shift[24]),
	.SDN(FE_OFN59_n51));
   DFCSNQD1 shift_reg_25_ (
	.CDN(FE_OFN62_n54),
	.CP(CTS_22),
	.D(N34),
	.Q(shift[25]),
	.SDN(FE_OFN61_n53));
   DFCSNQD1 shift_reg_26_ (
	.CDN(FE_PHN283_FE_OFN64_n56),
	.CP(CTS_22),
	.D(N35),
	.Q(shift[26]),
	.SDN(FE_OFN63_n55));
   DFCSNQD1 shift_reg_27_ (
	.CDN(FE_PHN222_FE_OFN66_n58),
	.CP(CTS_22),
	.D(N36),
	.Q(shift[27]),
	.SDN(FE_OFN65_n57));
   DFCSNQD1 shift_reg_28_ (
	.CDN(FE_PHN260_FE_OFN68_n60),
	.CP(CTS_22),
	.D(N37),
	.Q(shift[28]),
	.SDN(FE_OFN67_n59));
   DFCSNQD1 shift_reg_29_ (
	.CDN(FE_PHN243_FE_OFN70_n62),
	.CP(CTS_22),
	.D(N38),
	.Q(shift[29]),
	.SDN(FE_OFN69_n61));
   DFCSNQD1 shift_reg_30_ (
	.CDN(FE_PHN337_FE_OFN72_n64),
	.CP(CTS_22),
	.D(N39),
	.Q(FE_PHN376_shift_30),
	.SDN(FE_OFN71_n63));
   DFCSNQD1 shift_reg_31_ (
	.CDN(FE_PHN245_FE_OFN74_n66),
	.CP(CTS_22),
	.D(N40),
	.Q(shift[31]),
	.SDN(FE_OFN73_n65));
   DFCSNQD1 shift_reg_32_ (
	.CDN(FE_PHN262_FE_OFN76_n68),
	.CP(CTS_22),
	.D(N41),
	.Q(shift[32]),
	.SDN(FE_OFN75_n67));
   DFCSNQD1 shift_reg_33_ (
	.CDN(FE_PHN220_FE_OFN78_n70),
	.CP(CTS_22),
	.D(N42),
	.Q(FE_PHN364_shift_33),
	.SDN(FE_OFN77_n69));
   DFCSNQD1 shift_reg_34_ (
	.CDN(FE_PHN264_FE_OFN80_n72),
	.CP(CTS_22),
	.D(N43),
	.Q(shift[34]),
	.SDN(FE_OFN79_n71));
   DFCSNQD1 shift_reg_35_ (
	.CDN(FE_PHN248_FE_OFN82_n74),
	.CP(CTS_22),
	.D(N44),
	.Q(shift[35]),
	.SDN(FE_OFN81_n73));
   DFCSNQD1 shift_reg_36_ (
	.CDN(FE_OFN84_n76),
	.CP(CTS_22),
	.D(N45),
	.Q(shift[36]),
	.SDN(FE_OFN83_n75));
   DFCSNQD1 shift_reg_37_ (
	.CDN(FE_OFN86_n78),
	.CP(CTS_22),
	.D(N46),
	.Q(shift[37]),
	.SDN(FE_OFN85_n77));
   DFCSNQD2 shift_reg_38_ (
	.CDN(FE_OFN88_n80),
	.CP(CTS_22),
	.D(N47),
	.Q(shift[38]),
	.SDN(FE_OFN87_n79));
   DFCSNQD1 shift_reg_39_ (
	.CDN(FE_OFN90_n82),
	.CP(CTS_22),
	.D(N48),
	.Q(shift[39]),
	.SDN(FE_OFN89_n81));
   DFCSNQD1 shift_reg_40_ (
	.CDN(FE_PHN294_FE_OFN92_n84),
	.CP(CTS_22),
	.D(N49),
	.Q(shift[40]),
	.SDN(FE_OFN91_n83));
   DFCSNQD1 shift_reg_41_ (
	.CDN(FE_PHN261_FE_OFN94_n86),
	.CP(CTS_22),
	.D(N50),
	.Q(FE_PHN360_shift_41),
	.SDN(FE_OFN93_n85));
   DFCSNQD1 shift_reg_42_ (
	.CDN(FE_PHN217_FE_OFN96_n88),
	.CP(CTS_22),
	.D(N51),
	.Q(shift[42]),
	.SDN(FE_OFN95_n87));
   DFCSNQD1 shift_reg_43_ (
	.CDN(FE_PHN332_FE_OFN98_n90),
	.CP(CTS_22),
	.D(N52),
	.Q(shift[43]),
	.SDN(FE_OFN97_n89));
   DFCSNQD1 shift_reg_44_ (
	.CDN(FE_PHN218_FE_OFN100_n92),
	.CP(CTS_22),
	.D(N53),
	.Q(shift[44]),
	.SDN(FE_OFN99_n91));
   DFCSNQD1 shift_reg_45_ (
	.CDN(FE_PHN225_FE_OFN102_n94),
	.CP(CTS_22),
	.D(N54),
	.Q(shift[45]),
	.SDN(FE_OFN101_n93));
   DFCSNQD1 shift_reg_46_ (
	.CDN(FE_OFN104_n96),
	.CP(CTS_22),
	.D(N55),
	.Q(shift[46]),
	.SDN(FE_OFN103_n95));
   DFCSNQD1 shift_reg_47_ (
	.CDN(FE_OFN106_n98),
	.CP(CTS_22),
	.D(N56),
	.Q(shift[47]),
	.SDN(FE_OFN105_n97));
   DFCSNQD2 data_reg_47_ (
	.CDN(FE_OFN106_n98),
	.CP(CTS_19),
	.D(FE_PHN174_shift_47),
	.Q(FE_OFN0_data_47),
	.SDN(FE_OFN105_n97));
   DFCSNQD1 data_reg_46_ (
	.CDN(FE_OFN104_n96),
	.CP(CTS_19),
	.D(FE_PHN305_shift_46),
	.Q(FE_OFN1_data_46),
	.SDN(FE_OFN103_n95));
   DFCSNQD2 data_reg_45_ (
	.CDN(FE_PHN225_FE_OFN102_n94),
	.CP(CTS_19),
	.D(FE_PHN324_shift_45),
	.Q(FE_OFN2_data_45),
	.SDN(FE_OFN101_n93));
   DFCSNQD1 data_reg_44_ (
	.CDN(FE_PHN218_FE_OFN100_n92),
	.CP(CTS_19),
	.D(FE_PHN259_shift_44),
	.Q(FE_OFN3_data_44),
	.SDN(FE_OFN99_n91));
   DFCSNQD1 data_reg_43_ (
	.CDN(FE_PHN317_FE_OFN98_n90),
	.CP(CTS_19),
	.D(FE_PHN375_shift_43),
	.Q(FE_OFN4_data_43),
	.SDN(FE_OFN97_n89));
   DFCSNQD1 data_reg_35_ (
	.CDN(FE_PHN248_FE_OFN82_n74),
	.CP(CTS_19),
	.D(FE_PHN175_shift_35),
	.Q(FE_OFN12_data_35),
	.SDN(FE_OFN81_n73));
   DFCSNQD1 data_reg_34_ (
	.CDN(FE_PHN264_FE_OFN80_n72),
	.CP(CTS_19),
	.D(FE_PHN295_shift_34),
	.Q(FE_OFN13_data_34),
	.SDN(FE_OFN79_n71));
   DFCSNQD1 data_reg_33_ (
	.CDN(FE_PHN220_FE_OFN78_n70),
	.CP(CTS_19),
	.D(FE_PHN381_shift_33),
	.Q(FE_OFN14_data_33),
	.SDN(FE_OFN77_n69));
   DFCSNQD1 data_reg_32_ (
	.CDN(FE_PHN262_FE_OFN76_n68),
	.CP(CTS_19),
	.D(FE_PHN161_shift_32),
	.Q(FE_OFN15_data_32),
	.SDN(FE_OFN75_n67));
   DFCSNQD1 data_reg_31_ (
	.CDN(FE_PHN245_FE_OFN74_n66),
	.CP(CTS_19),
	.D(FE_PHN328_shift_31),
	.Q(FE_OFN16_data_31),
	.SDN(FE_OFN73_n65));
   DFCSNQD1 data_reg_30_ (
	.CDN(FE_PHN306_FE_OFN72_n64),
	.CP(CTS_19),
	.D(FE_PHN169_shift_30),
	.Q(FE_OFN17_data_30),
	.SDN(FE_OFN71_n63));
   DFCSNQD1 data_reg_29_ (
	.CDN(FE_PHN243_FE_OFN70_n62),
	.CP(CTS_19),
	.D(FE_PHN150_shift_29),
	.Q(FE_OFN18_data_29),
	.SDN(FE_OFN69_n61));
   DFCSNQD1 data_reg_28_ (
	.CDN(FE_PHN260_FE_OFN68_n60),
	.CP(CTS_19),
	.D(FE_PHN143_shift_28),
	.Q(FE_OFN19_data_28),
	.SDN(FE_OFN67_n59));
   DFCSNQD1 data_reg_27_ (
	.CDN(FE_PHN222_FE_OFN66_n58),
	.CP(CTS_19),
	.D(FE_PHN151_shift_27),
	.Q(FE_OFN20_data_27),
	.SDN(FE_OFN65_n57));
   DFCSNQD1 data_reg_26_ (
	.CDN(FE_PHN283_FE_OFN64_n56),
	.CP(CTS_19),
	.D(FE_PHN166_shift_26),
	.Q(FE_OFN21_data_26),
	.SDN(FE_OFN63_n55));
   DFCSNQD1 data_reg_25_ (
	.CDN(FE_OFN62_n54),
	.CP(CTS_19),
	.D(FE_PHN140_shift_25),
	.Q(FE_OFN22_data_25),
	.SDN(FE_OFN61_n53));
   DFCSNQD1 data_reg_24_ (
	.CDN(FE_PHN300_FE_OFN60_n52),
	.CP(CTS_19),
	.D(FE_PHN152_shift_24),
	.Q(FE_OFN23_data_24),
	.SDN(FE_OFN59_n51));
   DFCSNQD1 data_reg_23_ (
	.CDN(FE_OFN58_n50),
	.CP(CTS_19),
	.D(FE_PHN163_shift_23),
	.Q(FE_OFN24_data_23),
	.SDN(FE_OFN57_n49));
   DFCSNQD1 data_reg_22_ (
	.CDN(FE_PHN383_FE_OFN56_n48),
	.CP(CTS_19),
	.D(FE_PHN156_shift_22),
	.Q(FE_OFN25_data_22),
	.SDN(FE_OFN55_n47));
   DFCSNQD1 data_reg_21_ (
	.CDN(n46),
	.CP(CTS_19),
	.D(FE_PHN130_shift_21),
	.Q(FE_OFN26_data_21),
	.SDN(n45));
   DFCSNQD1 data_reg_20_ (
	.CDN(n44),
	.CP(CTS_19),
	.D(FE_PHN149_shift_20),
	.Q(FE_OFN27_data_20),
	.SDN(n43));
   DFCSNQD1 data_reg_19_ (
	.CDN(FE_PHN252_n42),
	.CP(CTS_19),
	.D(FE_PHN173_shift_19),
	.Q(FE_OFN28_data_19),
	.SDN(n41));
   DFCSNQD1 data_reg_18_ (
	.CDN(FE_PHN256_n40),
	.CP(CTS_19),
	.D(FE_PHN159_shift_18),
	.Q(FE_OFN29_data_18),
	.SDN(n39));
   DFCSNQD1 data_reg_17_ (
	.CDN(n38),
	.CP(CTS_19),
	.D(FE_PHN296_shift_17),
	.Q(FE_OFN30_data_17),
	.SDN(n37));
   DFCSNQD1 data_reg_16_ (
	.CDN(n36),
	.CP(CTS_19),
	.D(FE_PHN136_shift_16),
	.Q(FE_OFN31_data_16),
	.SDN(n35));
   DFCSNQD1 data_reg_15_ (
	.CDN(n34),
	.CP(CTS_19),
	.D(FE_PHN146_shift_15),
	.Q(FE_OFN32_data_15),
	.SDN(n33));
   DFCSNQD1 data_reg_14_ (
	.CDN(n32),
	.CP(CTS_19),
	.D(FE_PHN327_shift_14),
	.Q(FE_OFN33_data_14),
	.SDN(n31));
   DFCSNQD1 data_reg_13_ (
	.CDN(n30),
	.CP(CTS_19),
	.D(FE_PHN241_shift_13),
	.Q(FE_OFN34_data_13),
	.SDN(n29));
   DFCSNQD1 data_reg_12_ (
	.CDN(n28),
	.CP(CTS_19),
	.D(FE_PHN154_shift_12),
	.Q(FE_OFN35_data_12),
	.SDN(n27));
   DFCSNQD1 data_reg_11_ (
	.CDN(n26),
	.CP(CTS_19),
	.D(FE_PHN298_shift_11),
	.Q(FE_OFN36_data_11),
	.SDN(n25));
   DFCSNQD1 data_reg_10_ (
	.CDN(n24),
	.CP(CTS_19),
	.D(FE_PHN165_shift_10),
	.Q(FE_OFN37_data_10),
	.SDN(n23));
   DFCSNQD1 data_reg_9_ (
	.CDN(n22),
	.CP(CTS_19),
	.D(FE_PHN171_shift_9),
	.Q(FE_OFN38_data_9),
	.SDN(n21));
   DFCSNQD1 data_reg_8_ (
	.CDN(n20),
	.CP(CTS_19),
	.D(FE_PHN137_shift_8),
	.Q(FE_OFN39_data_8),
	.SDN(n19));
   DFCSNQD1 data_reg_7_ (
	.CDN(FE_PHN229_n18),
	.CP(CTS_19),
	.D(FE_PHN255_shift_7),
	.Q(FE_OFN40_data_7),
	.SDN(n17));
   DFCSNQD1 data_reg_6_ (
	.CDN(FE_PHN235_n16),
	.CP(CTS_19),
	.D(FE_PHN133_shift_6),
	.Q(FE_OFN41_data_6),
	.SDN(n15));
   DFCSNQD1 data_reg_5_ (
	.CDN(FE_PHN232_n14),
	.CP(CTS_19),
	.D(FE_PHN170_shift_5),
	.Q(FE_OFN42_data_5),
	.SDN(n13));
   DFCSNQD1 data_reg_4_ (
	.CDN(FE_PHN270_n12),
	.CP(CTS_19),
	.D(FE_PHN177_FE_OFN51_shift_4),
	.Q(FE_OFN43_data_4),
	.SDN(FE_PHN380_n11));
   DFCSNQD1 data_reg_3_ (
	.CDN(FE_PHN272_n10),
	.CP(CTS_19),
	.D(FE_PHN189_shift_3),
	.Q(FE_OFN44_data_3),
	.SDN(n9));
   DFCSNQD1 data_reg_2_ (
	.CDN(FE_PHN316_n8),
	.CP(CTS_19),
	.D(FE_PHN147_shift_2),
	.Q(FE_OFN45_data_2),
	.SDN(n7));
   DFCSNQD1 data_reg_1_ (
	.CDN(n6),
	.CP(CTS_19),
	.D(FE_PHN138_shift_1),
	.Q(FE_OFN46_data_1),
	.SDN(n5));
   DFCSNQD1 data_reg_0_ (
	.CDN(n4),
	.CP(CTS_19),
	.D(FE_PHN155_shift_0),
	.Q(FE_OFN47_data_0),
	.SDN(n3));
   DFCSNQD1 data_reg_36_ (
	.CDN(FE_OFN84_n76),
	.CP(CTS_19),
	.D(FE_PHN162_shift_36),
	.Q(FE_OFN11_data_36),
	.SDN(FE_OFN83_n75));
   DFCSNQD1 data_reg_37_ (
	.CDN(FE_OFN86_n78),
	.CP(CTS_19),
	.D(FE_PHN148_shift_37),
	.Q(FE_OFN10_data_37),
	.SDN(FE_OFN85_n77));
   DFCSNQD1 data_reg_38_ (
	.CDN(FE_OFN88_n80),
	.CP(CTS_19),
	.D(FE_PHN153_shift_38),
	.Q(FE_OFN9_data_38),
	.SDN(FE_OFN87_n79));
   DFCSNQD1 data_reg_39_ (
	.CDN(FE_OFN90_n82),
	.CP(CTS_19),
	.D(FE_PHN167_shift_39),
	.Q(FE_OFN8_data_39),
	.SDN(FE_OFN89_n81));
   DFCSNQD1 data_reg_40_ (
	.CDN(FE_PHN294_FE_OFN92_n84),
	.CP(CTS_19),
	.D(FE_PHN323_shift_40),
	.Q(FE_OFN7_data_40),
	.SDN(FE_OFN91_n83));
   DFCSNQD1 data_reg_41_ (
	.CDN(FE_PHN261_FE_OFN94_n86),
	.CP(CTS_19),
	.D(FE_PHN157_shift_41),
	.Q(FE_OFN6_data_41),
	.SDN(FE_OFN93_n85));
   DFCSNQD1 data_reg_42_ (
	.CDN(FE_PHN217_FE_OFN96_n88),
	.CP(CTS_19),
	.D(FE_PHN338_shift_42),
	.Q(FE_OFN5_data_42),
	.SDN(FE_OFN95_n87));
   EDFQD1 dout_reg (
	.CP(CTS_22),
	.D(shift[47]),
	.E(FE_OFN107_n113),
	.Q(FE_OFN50_dout));
   ND2D2 U155 (
	.A1(wr),
	.A2(FE_OFN108_FE_OFN48_load),
	.ZN(N7));
   IAO21D1 U159 (
	.A1(FE_OFN54_FE_DBTN0_load),
	.A2(wr),
	.B(reset),
	.ZN(n113));
   INVD1 U165 (
	.I(N7),
	.ZN(N8));
   ND2D0 U166 (
	.A1(reset),
	.A2(FE_PHN121_presetval_44),
	.ZN(n91));
   ND2D0 U167 (
	.A1(reset),
	.A2(FE_PHN179_presetval_39),
	.ZN(n81));
   ND2D0 U168 (
	.A1(reset),
	.A2(FE_PHN244_presetval_34),
	.ZN(n71));
   ND2D0 U169 (
	.A1(reset),
	.A2(FE_PHN186_presetval_29),
	.ZN(n61));
   ND2D0 U170 (
	.A1(reset),
	.A2(FE_PHN178_presetval_24),
	.ZN(n51));
   ND2D1 U171 (
	.A1(reset),
	.A2(FE_PHN240_presetval_19),
	.ZN(n41));
   ND2D1 U172 (
	.A1(reset),
	.A2(FE_PHN202_presetval_14),
	.ZN(n31));
   CKND2D2 U173 (
	.A1(reset),
	.A2(FE_PHN197_presetval_9),
	.ZN(n21));
   ND2D1 U174 (
	.A1(reset),
	.A2(FE_PHN176_presetval_4),
	.ZN(n11));
   TIEL U175 (
	.ZN(net40));
   CKND2D2 U176 (
	.A1(reset),
	.A2(FE_PHN198_presetval_0),
	.ZN(n3));
   CKND2D2 U177 (
	.A1(reset),
	.A2(FE_PHN199_presetval_1),
	.ZN(n5));
   ND2D1 U178 (
	.A1(reset),
	.A2(FE_PHN193_presetval_2),
	.ZN(n7));
   ND2D1 U179 (
	.A1(reset),
	.A2(FE_PHN114_presetval_3),
	.ZN(n9));
   ND2D1 U180 (
	.A1(reset),
	.A2(FE_PHN195_presetval_5),
	.ZN(n13));
   CKND2D2 U181 (
	.A1(reset),
	.A2(FE_PHN200_presetval_6),
	.ZN(n15));
   ND2D1 U182 (
	.A1(reset),
	.A2(FE_PHN196_presetval_7),
	.ZN(n17));
   ND2D1 U183 (
	.A1(reset),
	.A2(FE_PHN192_presetval_8),
	.ZN(n19));
   CKND2D2 U184 (
	.A1(reset),
	.A2(FE_PHN203_presetval_10),
	.ZN(n23));
   CKND2D2 U185 (
	.A1(reset),
	.A2(FE_PHN204_presetval_11),
	.ZN(n25));
   ND2D1 U186 (
	.A1(reset),
	.A2(FE_PHN191_presetval_12),
	.ZN(n27));
   ND2D1 U187 (
	.A1(reset),
	.A2(FE_PHN201_presetval_13),
	.ZN(n29));
   ND2D1 U188 (
	.A1(reset),
	.A2(FE_PHN257_presetval_15),
	.ZN(n33));
   ND2D0 U189 (
	.A1(reset),
	.A2(FE_PHN187_presetval_41),
	.ZN(n85));
   CKND2D2 U190 (
	.A1(reset),
	.A2(FE_PHN258_presetval_16),
	.ZN(n35));
   ND2D0 U191 (
	.A1(reset),
	.A2(FE_PHN118_presetval_33),
	.ZN(n69));
   ND2D0 U192 (
	.A1(reset),
	.A2(FE_PHN182_presetval_40),
	.ZN(n83));
   ND2D0 U193 (
	.A1(reset),
	.A2(FE_PHN117_presetval_47),
	.ZN(n97));
   ND2D1 U194 (
	.A1(reset),
	.A2(FE_PHN205_presetval_17),
	.ZN(n37));
   ND2D0 U195 (
	.A1(reset),
	.A2(FE_PHN181_presetval_31),
	.ZN(n65));
   ND2D0 U196 (
	.A1(reset),
	.A2(FE_PHN183_presetval_32),
	.ZN(n67));
   ND2D1 U197 (
	.A1(reset),
	.A2(FE_PHN194_presetval_18),
	.ZN(n39));
   ND2D0 U198 (
	.A1(reset),
	.A2(FE_PHN119_presetval_46),
	.ZN(n95));
   ND2D0 U199 (
	.A1(reset),
	.A2(FE_PHN120_presetval_26),
	.ZN(n55));
   ND2D0 U200 (
	.A1(reset),
	.A2(FE_PHN180_presetval_35),
	.ZN(n73));
   ND2D0 U201 (
	.A1(reset),
	.A2(FE_PHN127_presetval_38),
	.ZN(n79));
   ND2D0 U202 (
	.A1(reset),
	.A2(FE_PHN115_presetval_45),
	.ZN(n93));
   ND2D0 U203 (
	.A1(reset),
	.A2(FE_PHN122_presetval_42),
	.ZN(n87));
   ND2D0 U204 (
	.A1(reset),
	.A2(FE_PHN123_presetval_36),
	.ZN(n75));
   ND2D1 U205 (
	.A1(reset),
	.A2(FE_PHN190_presetval_20),
	.ZN(n43));
   ND2D0 U206 (
	.A1(reset),
	.A2(FE_PHN128_presetval_37),
	.ZN(n77));
   ND2D0 U207 (
	.A1(reset),
	.A2(FE_PHN129_presetval_30),
	.ZN(n63));
   ND2D1 U208 (
	.A1(reset),
	.A2(FE_PHN212_presetval_21),
	.ZN(n45));
   ND2D0 U209 (
	.A1(reset),
	.A2(FE_PHN185_presetval_28),
	.ZN(n59));
   ND2D0 U210 (
	.A1(reset),
	.A2(FE_PHN125_presetval_43),
	.ZN(n89));
   ND2D0 U211 (
	.A1(reset),
	.A2(FE_PHN116_presetval_22),
	.ZN(n47));
   ND2D0 U212 (
	.A1(reset),
	.A2(FE_PHN215_presetval_23),
	.ZN(n49));
   ND2D0 U213 (
	.A1(reset),
	.A2(FE_PHN124_presetval_25),
	.ZN(n53));
   ND2D0 U214 (
	.A1(reset),
	.A2(FE_PHN126_presetval_27),
	.ZN(n57));
   AO22D0 U215 (
	.A1(FE_PHN188_load),
	.A2(data[0]),
	.B1(FE_PHN322_din),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N9));
   AO22D0 U216 (
	.A1(FE_OFN48_load),
	.A2(data[1]),
	.B1(shift[0]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N10));
   AO22D0 U217 (
	.A1(FE_OFN48_load),
	.A2(data[2]),
	.B1(shift[1]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N11));
   AO22D1 U218 (
	.A1(FE_OFN48_load),
	.A2(data[3]),
	.B1(FE_PHN340_shift_2),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N12));
   AO22D0 U219 (
	.A1(FE_OFN48_load),
	.A2(FE_PHN365_FE_OFN43_data_4),
	.B1(shift[3]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N13));
   AO22D0 U220 (
	.A1(FE_OFN48_load),
	.A2(data[5]),
	.B1(FE_OFN51_shift_4),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N14));
   AO22D0 U221 (
	.A1(FE_OFN48_load),
	.A2(data[6]),
	.B1(shift[5]),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N15));
   AO22D0 U222 (
	.A1(FE_OFN48_load),
	.A2(data[7]),
	.B1(FE_PHN356_shift_6),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N16));
   AO22D1 U223 (
	.A1(FE_OFN48_load),
	.A2(data[8]),
	.B1(FE_PHN345_shift_7),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N17));
   AO22D0 U224 (
	.A1(FE_OFN48_load),
	.A2(data[9]),
	.B1(shift[8]),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N18));
   AO22D0 U225 (
	.A1(FE_OFN48_load),
	.A2(data[10]),
	.B1(shift[9]),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N19));
   AO22D0 U226 (
	.A1(FE_OFN48_load),
	.A2(data[11]),
	.B1(FE_PHN344_shift_10),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N20));
   AO22D0 U227 (
	.A1(FE_OFN48_load),
	.A2(data[12]),
	.B1(FE_PHN373_shift_11),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N21));
   AO22D0 U228 (
	.A1(FE_OFN48_load),
	.A2(FE_OFN34_data_13),
	.B1(FE_PHN342_shift_12),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(FE_PHN378_N22));
   AO22D0 U229 (
	.A1(FE_OFN48_load),
	.A2(data[14]),
	.B1(FE_PHN369_shift_13),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N23));
   AO22D0 U230 (
	.A1(FE_OFN48_load),
	.A2(FE_PHN362_FE_OFN32_data_15),
	.B1(shift[14]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N24));
   AO22D0 U232 (
	.A1(FE_OFN48_load),
	.A2(data[16]),
	.B1(shift[15]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N25));
   AO22D0 U233 (
	.A1(FE_OFN48_load),
	.A2(data[17]),
	.B1(FE_PHN297_shift_16),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N26));
   AO22D0 U234 (
	.A1(FE_OFN48_load),
	.A2(data[18]),
	.B1(FE_PHN374_shift_17),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N27));
   AO22D0 U235 (
	.A1(FE_OFN49_load),
	.A2(FE_OFN28_data_19),
	.B1(FE_PHN354_shift_18),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N28));
   AO22D0 U236 (
	.A1(FE_OFN49_load),
	.A2(FE_PHN367_FE_OFN27_data_20),
	.B1(shift[19]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N29));
   AO22D0 U237 (
	.A1(FE_OFN49_load),
	.A2(data[21]),
	.B1(shift[20]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N30));
   AO22D0 U238 (
	.A1(FE_OFN49_load),
	.A2(data[22]),
	.B1(FE_PHN343_shift_21),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N31));
   AO22D0 U239 (
	.A1(FE_OFN49_load),
	.A2(data[23]),
	.B1(shift[22]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N32));
   AO22D1 U241 (
	.A1(FE_OFN49_load),
	.A2(data[24]),
	.B1(FE_PHN335_shift_23),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N33));
   AO22D0 U242 (
	.A1(FE_OFN48_load),
	.A2(data[25]),
	.B1(FE_PHN346_shift_24),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N34));
   AO22D0 U243 (
	.A1(FE_OFN48_load),
	.A2(data[26]),
	.B1(shift[25]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N35));
   AO22D0 U244 (
	.A1(FE_OFN48_load),
	.A2(data[27]),
	.B1(FE_PHN359_shift_26),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N36));
   AO22D0 U245 (
	.A1(FE_OFN48_load),
	.A2(data[28]),
	.B1(FE_PHN349_shift_27),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N37));
   AO22D0 U246 (
	.A1(FE_OFN48_load),
	.A2(data[29]),
	.B1(FE_PHN357_shift_28),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N38));
   AO22D0 U247 (
	.A1(FE_PHN188_load),
	.A2(data[30]),
	.B1(shift[29]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N39));
   AO22D0 U248 (
	.A1(FE_PHN188_load),
	.A2(data[31]),
	.B1(shift[30]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N40));
   AO22D0 U250 (
	.A1(FE_PHN188_load),
	.A2(data[32]),
	.B1(shift[31]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N41));
   AO22D0 U251 (
	.A1(FE_OFN48_load),
	.A2(data[33]),
	.B1(FE_PHN352_shift_32),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N42));
   AO22D0 U252 (
	.A1(FE_OFN48_load),
	.A2(data[34]),
	.B1(shift[33]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N43));
   AO22D0 U253 (
	.A1(FE_OFN48_load),
	.A2(data[35]),
	.B1(FE_PHN372_shift_34),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N44));
   AO22D0 U254 (
	.A1(FE_OFN48_load),
	.A2(data[36]),
	.B1(FE_PHN363_shift_35),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N45));
   AO22D0 U255 (
	.A1(FE_OFN48_load),
	.A2(data[37]),
	.B1(shift[36]),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N46));
   AO22D0 U256 (
	.A1(FE_OFN48_load),
	.A2(data[38]),
	.B1(FE_PHN382_shift_37),
	.B2(FE_OFN53_FE_DBTN0_load),
	.Z(N47));
   AO22D0 U257 (
	.A1(FE_OFN48_load),
	.A2(data[39]),
	.B1(shift[38]),
	.B2(FE_OFN52_FE_DBTN0_load),
	.Z(N48));
   AO22D0 U259 (
	.A1(FE_OFN48_load),
	.A2(data[40]),
	.B1(FE_PHN351_shift_39),
	.B2(FE_DBTN0_load),
	.Z(N49));
   AO22D0 U260 (
	.A1(FE_OFN108_FE_OFN48_load),
	.A2(data[41]),
	.B1(shift[40]),
	.B2(FE_DBTN0_load),
	.Z(N50));
   AO22D0 U261 (
	.A1(FE_OFN108_FE_OFN48_load),
	.A2(data[42]),
	.B1(shift[41]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N51));
   AO22D0 U262 (
	.A1(FE_OFN108_FE_OFN48_load),
	.A2(data[43]),
	.B1(shift[42]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N52));
   AO22D0 U263 (
	.A1(FE_OFN49_load),
	.A2(FE_PHN366_FE_OFN3_data_44),
	.B1(shift[43]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N53));
   AO22D0 U264 (
	.A1(FE_OFN49_load),
	.A2(FE_OFN2_data_45),
	.B1(FE_PHN371_shift_44),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N54));
   AO22D0 U265 (
	.A1(FE_OFN49_load),
	.A2(data[46]),
	.B1(shift[45]),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N55));
   AO22D0 U266 (
	.A1(FE_OFN49_load),
	.A2(FE_OFN0_data_47),
	.B1(FE_PHN370_shift_46),
	.B2(FE_OFN54_FE_DBTN0_load),
	.Z(N56));
   IND2D0 U267 (
	.A1(FE_PHN117_presetval_47),
	.B1(reset),
	.ZN(n98));
   IND2D0 U268 (
	.A1(FE_PHN119_presetval_46),
	.B1(reset),
	.ZN(n96));
   IND2D0 U269 (
	.A1(FE_PHN115_presetval_45),
	.B1(reset),
	.ZN(n94));
   IND2D0 U270 (
	.A1(FE_PHN121_presetval_44),
	.B1(reset),
	.ZN(n92));
   IND2D0 U271 (
	.A1(FE_PHN125_presetval_43),
	.B1(reset),
	.ZN(n90));
   IND2D0 U272 (
	.A1(FE_PHN122_presetval_42),
	.B1(reset),
	.ZN(n88));
   IND2D0 U273 (
	.A1(FE_PHN187_presetval_41),
	.B1(reset),
	.ZN(n86));
   IND2D0 U274 (
	.A1(FE_PHN182_presetval_40),
	.B1(reset),
	.ZN(n84));
   IND2D0 U275 (
	.A1(FE_PHN179_presetval_39),
	.B1(reset),
	.ZN(n82));
   IND2D0 U276 (
	.A1(FE_PHN127_presetval_38),
	.B1(reset),
	.ZN(n80));
   IND2D0 U277 (
	.A1(FE_PHN128_presetval_37),
	.B1(reset),
	.ZN(n78));
   IND2D0 U278 (
	.A1(FE_PHN123_presetval_36),
	.B1(reset),
	.ZN(n76));
   IND2D0 U279 (
	.A1(FE_PHN180_presetval_35),
	.B1(reset),
	.ZN(n74));
   IND2D0 U280 (
	.A1(FE_PHN244_presetval_34),
	.B1(reset),
	.ZN(n72));
   IND2D0 U281 (
	.A1(FE_PHN118_presetval_33),
	.B1(reset),
	.ZN(n70));
   IND2D0 U282 (
	.A1(FE_PHN183_presetval_32),
	.B1(reset),
	.ZN(FE_PHN320_n68));
   IND2D0 U283 (
	.A1(FE_PHN181_presetval_31),
	.B1(reset),
	.ZN(n66));
   IND2D0 U284 (
	.A1(FE_PHN129_presetval_30),
	.B1(reset),
	.ZN(n64));
   IND2D0 U285 (
	.A1(FE_PHN186_presetval_29),
	.B1(reset),
	.ZN(n62));
   IND2D0 U286 (
	.A1(FE_PHN185_presetval_28),
	.B1(reset),
	.ZN(n60));
   IND2D0 U287 (
	.A1(FE_PHN126_presetval_27),
	.B1(reset),
	.ZN(n58));
   IND2D0 U288 (
	.A1(FE_PHN120_presetval_26),
	.B1(reset),
	.ZN(n56));
   IND2D0 U289 (
	.A1(FE_PHN124_presetval_25),
	.B1(reset),
	.ZN(n54));
   IND2D0 U290 (
	.A1(FE_PHN319_presetval_24),
	.B1(reset),
	.ZN(n52));
   IND2D0 U291 (
	.A1(FE_PHN215_presetval_23),
	.B1(reset),
	.ZN(n50));
   IND2D0 U292 (
	.A1(FE_PHN116_presetval_22),
	.B1(reset),
	.ZN(n48));
   IND2D2 U293 (
	.A1(FE_PHN212_presetval_21),
	.B1(reset),
	.ZN(n46));
   IND2D2 U294 (
	.A1(FE_PHN190_presetval_20),
	.B1(reset),
	.ZN(n44));
   IND2D2 U295 (
	.A1(FE_PHN267_presetval_19),
	.B1(reset),
	.ZN(n42));
   IND2D2 U296 (
	.A1(FE_PHN194_presetval_18),
	.B1(reset),
	.ZN(n40));
   IND2D2 U297 (
	.A1(FE_PHN205_presetval_17),
	.B1(reset),
	.ZN(n38));
   IND2D2 U298 (
	.A1(FE_PHN258_presetval_16),
	.B1(reset),
	.ZN(n36));
   IND2D2 U299 (
	.A1(FE_PHN257_presetval_15),
	.B1(reset),
	.ZN(n34));
   IND2D2 U300 (
	.A1(FE_PHN223_presetval_14),
	.B1(reset),
	.ZN(n32));
   IND2D2 U301 (
	.A1(FE_PHN224_presetval_13),
	.B1(reset),
	.ZN(n30));
   IND2D2 U302 (
	.A1(FE_PHN191_presetval_12),
	.B1(reset),
	.ZN(n28));
   IND2D2 U303 (
	.A1(FE_PHN204_presetval_11),
	.B1(reset),
	.ZN(n26));
   IND2D2 U304 (
	.A1(FE_PHN203_presetval_10),
	.B1(reset),
	.ZN(n24));
   IND2D2 U305 (
	.A1(FE_PHN226_presetval_9),
	.B1(reset),
	.ZN(n22));
   IND2D2 U306 (
	.A1(FE_PHN192_presetval_8),
	.B1(reset),
	.ZN(n20));
   IND2D2 U307 (
	.A1(FE_PHN196_presetval_7),
	.B1(reset),
	.ZN(n18));
   IND2D2 U308 (
	.A1(FE_PHN200_presetval_6),
	.B1(reset),
	.ZN(n16));
   IND2D2 U309 (
	.A1(FE_PHN195_presetval_5),
	.B1(reset),
	.ZN(n14));
   IND2D2 U310 (
	.A1(FE_PHN176_presetval_4),
	.B1(reset),
	.ZN(n12));
   IND2D2 U311 (
	.A1(FE_PHN114_presetval_3),
	.B1(reset),
	.ZN(n10));
   IND2D2 U312 (
	.A1(FE_PHN193_presetval_2),
	.B1(reset),
	.ZN(n8));
   IND2D2 U313 (
	.A1(FE_PHN281_presetval_1),
	.B1(reset),
	.ZN(n6));
   IND2D2 U314 (
	.A1(FE_PHN227_presetval_0),
	.B1(reset),
	.ZN(n4));

endmodule

