/*
###############################################################
#  Generated by:      Cadence Innovus 16.11-s067_1
#  OS:                Linux x86_64(Host ID linrack5.ee.columbia.edu)
#  Generated on:      Wed Nov  2 10:26:22 2016
#  Design:            johnsonCounter
#  Command:           saveNetlist ./OUTPUT_1101_johnsonCounter_00/1101_johnsonCounter_00.phy.v -phys -excludeLeafCell -excludeCellInst {FILL1 FILL2 FILL4 FILL8 FILL16 FILL32 FILL64}
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : L-2016.03-SP5
// Date      : Tue Nov  1 17:28:30 2016
/////////////////////////////////////////////////////////////
module johnsonCounter_phy (
	Clock, 
	rst, 
	Count_out);
	
   input Clock;
   input rst;
   output [7:0] Count_out;


   // Internal wires
   wire FE_PDN7_Count_out_3;
   wire FE_PHN6_Count_out_1;
   wire FE_PHN5_Count_out_2;
   wire FE_PHN4_Count_out_0;
   wire FE_DBTN0_rst;
   wire n5;
   wire n6;
   wire n7;
   wire n8;

   // Module instantiations
   BUFFD4 FE_PDC8_Count_out_3 (
	.I(FE_PDN7_Count_out_3),
	.Z(Count_out[3]));
   BUFFD0 FE_PHC6_Count_out_1 (
	.I(Count_out[1]),
	.Z(FE_PHN6_Count_out_1));
   BUFFD0 FE_PHC5_Count_out_2 (
	.I(Count_out[2]),
	.Z(FE_PHN5_Count_out_2));
   BUFFD0 FE_PHC4_Count_out_0 (
	.I(Count_out[0]),
	.Z(FE_PHN4_Count_out_0));
   CKND4 FE_DBTC0_rst (
	.CLK(rst),
	.CN(FE_DBTN0_rst));
   DFCND4 Count_temp_reg_0_ (
	.CDN(FE_DBTN0_rst),
	.CP(Clock),
	.D(n5),
	.Q(Count_out[0]),
	.QN(n8));
   DFCNQD4 Count_temp_reg_3_ (
	.CDN(FE_DBTN0_rst),
	.CP(Clock),
	.D(FE_PHN5_Count_out_2),
	.Q(FE_PDN7_Count_out_3));
   EDFQD4 Count_temp_bar_reg_0_ (
	.CP(Clock),
	.D(Count_out[3]),
	.E(FE_DBTN0_rst),
	.Q(Count_out[4]));
   DFCNQD4 Count_temp_reg_2_ (
	.CDN(FE_DBTN0_rst),
	.CP(Clock),
	.D(FE_PHN6_Count_out_1),
	.Q(Count_out[2]));
   DFCNQD4 Count_temp_reg_1_ (
	.CDN(FE_DBTN0_rst),
	.CP(Clock),
	.D(FE_PHN4_Count_out_0),
	.Q(Count_out[1]));
   EDFQD4 Count_temp_bar_reg_1_ (
	.CP(Clock),
	.D(n8),
	.E(FE_DBTN0_rst),
	.Q(Count_out[5]));
   EDFQD4 Count_temp_bar_reg_2_ (
	.CP(Clock),
	.D(n7),
	.E(FE_DBTN0_rst),
	.Q(Count_out[6]));
   EDFQD4 Count_temp_bar_reg_3_ (
	.CP(Clock),
	.D(n6),
	.E(FE_DBTN0_rst),
	.Q(Count_out[7]));
   INVD0 U10 (
	.I(Count_out[1]),
	.ZN(n7));
   INVD0 U11 (
	.I(Count_out[2]),
	.ZN(n6));
   INVD0 U12 (
	.I(Count_out[3]),
	.ZN(n5));

endmodule

