/*
###############################################################
#  Generated by:      Cadence Innovus 16.11-s067_1
#  OS:                Linux x86_64(Host ID linrack4.ee.columbia.edu)
#  Generated on:      Sat Nov  5 19:33:34 2016
#  Design:            TCU_v4
#  Command:           saveNetlist ./OUTPUT_1105_00_TCU/1105_00_TCU.phy.v -phys -excludeLeafCell -excludeCellInst {FILL1 FILL2 FILL4 FILL8 FILL16 FILL32 FILL64}
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : L-2016.03-SP5
// Date      : Fri Nov  4 20:04:53 2016
/////////////////////////////////////////////////////////////
module SNPS_CLOCK_GATE_HIGH_TCU_v4 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;


   // Module instantiations
   CKLNQD6 latch (
	.CP(CLK),
	.E(EN),
	.Q(ENCLK),
	.TE(TE));
endmodule

module TCU_v4_phy (
	reset, 
	ref_clk, 
	clk_in, 
	delay, 
	width, 
	outClk);
   input reset;
   input ref_clk;
   input clk_in;
   input [5:0] delay;
   input [5:0] width;
   output outClk;

   // Internal wires
   wire FE_OFN40_clkPass;
   wire CTS_8;
   wire CTS_7;
   wire FE_OFN39_n53;
   wire FE_OFN38_n47;
   wire FE_OFN37_n42;
   wire FE_OFN35_n39;
   wire FE_OCPN34_ref_clk;
   wire FE_OCPN33_clkPass;
   wire FE_OFN31_clk_counter_2;
   wire FE_OFN30_n24;
   wire FE_OFN29_n53;
   wire FE_OFN28_n42;
   wire FE_OFN26_n39;
   wire FE_OFN25_n34;
   wire FE_OFN23_width_reg_2;
   wire FE_OFN22_width_reg_3;
   wire FE_OFN21_width_reg_5;
   wire FE_OFN20_delay_reg_0;
   wire FE_OFN19_clk_counter_0;
   wire FE_OFN18_n63;
   wire FE_OFN15_n71;
   wire FE_OFN14_n66;
   wire FE_OFN11_n32;
   wire FE_OFN10_n69;
   wire FE_OFN9_width_reg_0;
   wire FE_OFN7_delay_reg_1;
   wire FE_OFN6_delay_reg_2;
   wire FE_OFN4_delay_reg_5;
   wire FE_OFN3_clk_counter_4;
   wire FE_OFN2_clk_counter_6;
   wire FE_OFN1_n20;
   wire FE_OFN0_outClk;
   wire done;
   wire clkPass;
   wire N10;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N47;
   wire N52;
   wire net66;
   wire net67;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n28;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire [6:0] clk_counter;
   wire [5:0] delay_reg;
   wire [5:0] width_reg;

   // Module instantiations
   BUFFD0 FE_OFC40_clkPass (
	.I(clkPass),
	.Z(FE_OFN40_clkPass));
   CKNXD0 CTS_ccd_INV_clk_in_G0_L2_1 (
	.I(CTS_8),
	.ZN(CTS_7));
   CKNXD0 CTS_cci_INV_clk_in_G0_L1_1 (
	.I(clk_in),
	.ZN(CTS_8));
   BUFFD0 FE_OFC39_n53 (
	.I(n53),
	.Z(FE_OFN39_n53));
   BUFFD0 FE_OFC38_n47 (
	.I(n47),
	.Z(FE_OFN38_n47));
   BUFFD0 FE_OFC37_n42 (
	.I(n42),
	.Z(FE_OFN37_n42));
   BUFFD0 FE_OFC35_n39 (
	.I(n39),
	.Z(FE_OFN35_n39));
   BUFFD0 FE_OCPC34_ref_clk (
	.I(ref_clk),
	.Z(FE_OCPN34_ref_clk));
   BUFFD0 FE_OCPC33_clkPass (
	.I(clkPass),
	.Z(FE_OCPN33_clkPass));
   BUFFD0 FE_OFC31_clk_counter_2 (
	.I(clk_counter[2]),
	.Z(FE_OFN31_clk_counter_2));
   XOR2D1 FE_RC_4_0 (
	.A1(n67),
	.A2(delay_reg[3]),
	.Z(n55));
   XOR2D1 FE_RC_3_0 (
	.A1(n45),
	.A2(FE_OFN3_clk_counter_4),
	.Z(n58));
   XOR2D1 FE_RC_2_0 (
	.A1(width_reg[1]),
	.A2(n33),
	.Z(n35));
   XOR2D2 FE_RC_1_0 (
	.A1(clk_counter[5]),
	.A2(FE_OFN4_delay_reg_5),
	.Z(n60));
   XNR2D1 FE_RC_0_0 (
	.A1(FE_OFN31_clk_counter_2),
	.A2(FE_OFN6_delay_reg_2),
	.ZN(n57));
   BUFFD2 FE_OFC30_n24 (
	.I(n24),
	.Z(FE_OFN30_n24));
   BUFFD2 FE_OFC29_n53 (
	.I(FE_OFN39_n53),
	.Z(FE_OFN29_n53));
   BUFFD2 FE_OFC28_n42 (
	.I(FE_OFN37_n42),
	.Z(FE_OFN28_n42));
   BUFFD2 FE_OFC26_n39 (
	.I(FE_OFN35_n39),
	.Z(FE_OFN26_n39));
   BUFFD0 FE_OFC25_n34 (
	.I(n34),
	.Z(FE_OFN25_n34));
   BUFFD2 FE_OFC23_width_reg_2 (
	.I(width_reg[2]),
	.Z(FE_OFN23_width_reg_2));
   BUFFD2 FE_OFC22_width_reg_3 (
	.I(width_reg[3]),
	.Z(FE_OFN22_width_reg_3));
   BUFFD2 FE_OFC21_width_reg_5 (
	.I(width_reg[5]),
	.Z(FE_OFN21_width_reg_5));
   BUFFD2 FE_OFC20_delay_reg_0 (
	.I(delay_reg[0]),
	.Z(FE_OFN20_delay_reg_0));
   BUFFD2 FE_OFC19_clk_counter_0 (
	.I(clk_counter[0]),
	.Z(FE_OFN19_clk_counter_0));
   BUFFD2 FE_OFC18_n63 (
	.I(n63),
	.Z(FE_OFN18_n63));
   BUFFD2 FE_OFC15_n71 (
	.I(n71),
	.Z(FE_OFN15_n71));
   BUFFD2 FE_OFC14_n66 (
	.I(n66),
	.Z(FE_OFN14_n66));
   BUFFD2 FE_OFC11_n32 (
	.I(n32),
	.Z(FE_OFN11_n32));
   BUFFD2 FE_OFC10_n69 (
	.I(n69),
	.Z(FE_OFN10_n69));
   BUFFD3 FE_OFC9_width_reg_0 (
	.I(width_reg[0]),
	.Z(FE_OFN9_width_reg_0));
   BUFFD2 FE_OFC7_delay_reg_1 (
	.I(delay_reg[1]),
	.Z(FE_OFN7_delay_reg_1));
   BUFFD2 FE_OFC6_delay_reg_2 (
	.I(delay_reg[2]),
	.Z(FE_OFN6_delay_reg_2));
   BUFFD2 FE_OFC4_delay_reg_5 (
	.I(delay_reg[5]),
	.Z(FE_OFN4_delay_reg_5));
   BUFFD2 FE_OFC3_clk_counter_4 (
	.I(clk_counter[4]),
	.Z(FE_OFN3_clk_counter_4));
   BUFFD3 FE_OFC2_clk_counter_6 (
	.I(clk_counter[6]),
	.Z(FE_OFN2_clk_counter_6));
   BUFFD2 FE_OFC1_n20 (
	.I(n20),
	.Z(FE_OFN1_n20));
   BUFFD6 FE_OFC0_outClk (
	.I(FE_OFN0_outClk),
	.Z(outClk));
   LNQD1 delay_reg_reg_5_ (
	.D(delay[5]),
	.EN(reset),
	.Q(delay_reg[5]));
   LNQD1 delay_reg_reg_4_ (
	.D(delay[4]),
	.EN(reset),
	.Q(delay_reg[4]));
   LNQD2 delay_reg_reg_3_ (
	.D(delay[3]),
	.EN(reset),
	.Q(delay_reg[3]));
   LNQD1 delay_reg_reg_2_ (
	.D(delay[2]),
	.EN(reset),
	.Q(delay_reg[2]));
   LNQD1 delay_reg_reg_1_ (
	.D(delay[1]),
	.EN(reset),
	.Q(delay_reg[1]));
   LNQD1 delay_reg_reg_0_ (
	.D(delay[0]),
	.EN(reset),
	.Q(delay_reg[0]));
   LNQD1 width_reg_reg_5_ (
	.D(width[5]),
	.EN(reset),
	.Q(width_reg[5]));
   LNQD1 width_reg_reg_4_ (
	.D(width[4]),
	.EN(reset),
	.Q(width_reg[4]));
   LNQD1 width_reg_reg_3_ (
	.D(width[3]),
	.EN(reset),
	.Q(width_reg[3]));
   LNQD1 width_reg_reg_2_ (
	.D(width[2]),
	.EN(reset),
	.Q(width_reg[2]));
   LNQD1 width_reg_reg_1_ (
	.D(width[1]),
	.EN(reset),
	.Q(width_reg[1]));
   LNQD1 width_reg_reg_0_ (
	.D(width[0]),
	.EN(reset),
	.Q(width_reg[0]));
   DFCNQD1 clk_counter_reg_6_ (
	.CDN(reset),
	.CP(net66),
	.D(N31),
	.Q(clk_counter[6]));
   DFCNQD1 clk_counter_reg_5_ (
	.CDN(reset),
	.CP(net66),
	.D(N30),
	.Q(clk_counter[5]));
   DFCNQD1 clk_counter_reg_4_ (
	.CDN(reset),
	.CP(net66),
	.D(N29),
	.Q(clk_counter[4]));
   DFCNQD1 clk_counter_reg_3_ (
	.CDN(reset),
	.CP(net66),
	.D(N28),
	.Q(clk_counter[3]));
   DFCNQD1 clk_counter_reg_2_ (
	.CDN(reset),
	.CP(net66),
	.D(N27),
	.Q(clk_counter[2]));
   DFCNQD1 clk_counter_reg_1_ (
	.CDN(reset),
	.CP(net66),
	.D(N26),
	.Q(clk_counter[1]));
   DFCNQD1 clk_counter_reg_0_ (
	.CDN(reset),
	.CP(net66),
	.D(N25),
	.Q(clk_counter[0]));
   EDFCNQD1 outClk_reg (
	.CDN(reset),
	.CP(CTS_7),
	.D(n17),
	.E(FE_OFN40_clkPass),
	.Q(FE_OFN0_outClk));
   NR2XD0 U30 (
	.A1(n67),
	.A2(n68),
	.ZN(n66));
   XOR2D1 U32 (
	.A1(FE_OFN21_width_reg_5),
	.A2(n60),
	.Z(n50));
   NR2XD0 U33 (
	.A1(n70),
	.A2(N25),
	.ZN(n69));
   XOR2D2 U34 (
	.A1(n46),
	.A2(n58),
	.Z(n48));
   CKNXD1 U35 (
	.I(clk_counter[1]),
	.ZN(n70));
   CKNXD1 U37 (
	.I(clk_counter[3]),
	.ZN(n67));
   AOI211XD4 U40 (
	.A1(n54),
	.A2(FE_OFN2_clk_counter_6),
	.B(FE_OFN29_n53),
	.C(n52),
	.ZN(n24));
   AOI211XD4 U41 (
	.A1(FE_OFN9_width_reg_0),
	.A2(n40),
	.B(FE_OFN26_n39),
	.C(n38),
	.ZN(n42));
   XNR2D2 U45 (
	.A1(n31),
	.A2(n57),
	.ZN(n43));
   XNR2D2 U46 (
	.A1(FE_OFN22_width_reg_3),
	.A2(n55),
	.ZN(n36));
   OAI21D2 U47 (
	.A1(n54),
	.A2(FE_OFN2_clk_counter_6),
	.B(FE_OFN30_n24),
	.ZN(n63));
   NR4D8 U48 (
	.A1(FE_OFN2_clk_counter_6),
	.A2(n60),
	.A3(n25),
	.A4(n59),
	.ZN(n62));
   INVD2 U49 (
	.I(clk_counter[5]),
	.ZN(n64));
   ND2D1 U52 (
	.A1(n22),
	.A2(FE_OFN1_n20),
	.ZN(n18));
   INVD0 U53 (
	.I(reset),
	.ZN(n21));
   AO21D1 U54 (
	.A1(FE_OFN19_clk_counter_0),
	.A2(FE_OFN20_delay_reg_0),
	.B(n40),
	.Z(n23));
   INVD1 U55 (
	.I(n23),
	.ZN(n25));
   FCICOND2 U56 (
	.A(FE_OFN4_delay_reg_5),
	.B(FE_OFN21_width_reg_5),
	.CI(n44),
	.CON(n54));
   INVD0 U58 (
	.I(n31),
	.ZN(n26));
   INVD0 U63 (
	.I(n37),
	.ZN(n28));
   OAI22D2 U65 (
	.A1(FE_OFN9_width_reg_0),
	.A2(n23),
	.B1(N25),
	.B2(FE_OFN11_n32),
	.ZN(n39));
   OAI221D4 U67 (
	.A1(n37),
	.A2(n36),
	.B1(n56),
	.B2(n35),
	.C(FE_OFN25_n34),
	.ZN(n38));
   IAO22D2 U68 (
	.A1(n70),
	.A2(FE_OFN7_delay_reg_1),
	.B1(FE_OFN7_delay_reg_1),
	.B2(n70),
	.ZN(n56));
   OAI221D4 U69 (
	.A1(n51),
	.A2(n50),
	.B1(n49),
	.B2(n48),
	.C(FE_OFN38_n47),
	.ZN(n52));
   FCICOND2 U70 (
	.A(n49),
	.B(n45),
	.CI(n46),
	.CON(n44));
   FCICOND2 U71 (
	.A(delay_reg[3]),
	.B(FE_OFN22_width_reg_3),
	.CI(n28),
	.CON(n49));
   ND4D8 U72 (
	.A1(n58),
	.A2(n57),
	.A3(n56),
	.A4(n55),
	.ZN(n59));
   TIEL U74 (
	.ZN(net67));
   ND2D0 U75 (
	.A1(FE_OFN20_delay_reg_0),
	.A2(FE_OFN9_width_reg_0),
	.ZN(n32));
   INVD1 U76 (
	.I(FE_OFN11_n32),
	.ZN(n33));
   MAOI222D2 U77 (
	.A(FE_OFN7_delay_reg_1),
	.B(n33),
	.C(width_reg[1]),
	.ZN(n31));
   MAOI222D2 U78 (
	.A(n26),
	.B(FE_OFN6_delay_reg_2),
	.C(FE_OFN23_width_reg_2),
	.ZN(n37));
   INVD1 U79 (
	.I(delay_reg[4]),
	.ZN(n45));
   CKNXD0 U80 (
	.I(width_reg[4]),
	.ZN(n46));
   AOI22D2 U81 (
	.A1(n37),
	.A2(n36),
	.B1(n35),
	.B2(n56),
	.ZN(n34));
   INVD1 U82 (
	.I(n44),
	.ZN(n51));
   AOI22D2 U83 (
	.A1(n51),
	.A2(n50),
	.B1(n49),
	.B2(n48),
	.ZN(n47));
   AO21D0 U84 (
	.A1(FE_OFN18_n63),
	.A2(outClk),
	.B(n62),
	.Z(n17));
   AOI21D4 U85 (
	.A1(n64),
	.A2(n65),
	.B(FE_OFN15_n71),
	.ZN(N30));
   OA21D0 U86 (
	.A1(FE_OFN3_clk_counter_4),
	.A2(FE_OFN14_n66),
	.B(n65),
	.Z(N29));
   AOI21D2 U87 (
	.A1(n67),
	.A2(n68),
	.B(FE_OFN14_n66),
	.ZN(N28));
   OA21D0 U88 (
	.A1(clk_counter[2]),
	.A2(FE_OFN10_n69),
	.B(n68),
	.Z(N27));
   AOI21D2 U89 (
	.A1(n70),
	.A2(N25),
	.B(FE_OFN10_n69),
	.ZN(N26));
   XOR2D0 U42 (
	.A1(FE_OFN2_clk_counter_6),
	.A2(FE_OFN15_n71),
	.Z(N31));
   SNPS_CLOCK_GATE_HIGH_TCU_v4 clk_gate_clk_counter_reg (
	.CLK(clk_in),
	.EN(N52),
	.ENCLK(net66),
	.TE(net67));
   LHQD1 clkPass_reg (
	.D(N10),
	.E(n18),
	.Q(clkPass));
   EDFCNQD1 done_reg (
	.CDN(reset),
	.CP(CTS_7),
	.D(N47),
	.E(clkPass),
	.Q(done));
   CKND2D2 U31 (
	.A1(clk_counter[2]),
	.A2(FE_OFN10_n69),
	.ZN(n68));
   CKND2D2 U29 (
	.A1(FE_OFN3_clk_counter_4),
	.A2(FE_OFN14_n66),
	.ZN(n65));
   NR2XD0 U73 (
	.A1(n64),
	.A2(n65),
	.ZN(n71));
   ND2D2 U44 (
	.A1(FE_OFN23_width_reg_2),
	.A2(n43),
	.ZN(n41));
   OAI211D4 U28 (
	.A1(FE_OFN23_width_reg_2),
	.A2(n43),
	.B(FE_OFN28_n42),
	.C(n41),
	.ZN(n53));
   NR2XD2 U39 (
	.A1(FE_OFN18_n63),
	.A2(n62),
	.ZN(N47));
   INR2XD1 U27 (
	.A1(FE_OCPN33_clkPass),
	.B1(N47),
	.ZN(N52));
   NR2D1 U25 (
	.A1(n21),
	.A2(done),
	.ZN(n20));
   INVD2 U38 (
	.I(FE_OFN19_clk_counter_0),
	.ZN(N25));
   ND2D4 U36 (
	.A1(ref_clk),
	.A2(FE_OFN1_n20),
	.ZN(n19));
   CKND0 U43 (
	.CLK(FE_OCPN34_ref_clk),
	.CN(n22));
   CKND1 U50 (
	.CLK(n19),
	.CN(N10));
   NR2XD3 U51 (
	.A1(FE_OFN20_delay_reg_0),
	.A2(FE_OFN19_clk_counter_0),
	.ZN(n40));

endmodule

