/*
###############################################################
#  Generated by:      Cadence Innovus 16.11-s067_1
#  OS:                Linux x86_64(Host ID linrack4.ee.columbia.edu)
#  Generated on:      Wed Nov  9 15:33:32 2016
#  Design:            PI_dig_frontend
#  Command:           saveNetlist ./OUTPUT_1109_PI_dig_frontend_00_iofix/1109_PI_dig_frontend_00_iofix.phy.v -phys -excludeLeafCell -excludeCellInst {FILL1 FILL2 FILL4 FILL8 FILL16 FILL32 FILL64}
###############################################################
*/

//The johnsoncounter toggles with frequency of CLKIN
//CLK_A and CLK_B both count with half frequency of CLKIN

module PI_dig_frontend_phy (
	CLK_A, 
	CLK_B, 
	SEL, 
	SEL_SIDE, 
	DIV, 
	PH_SEL);
   output [0:2] CLK_A;
   output [0:2] CLK_B;
   output [1:32] SEL;
   output [1:32] SEL_SIDE;
   input [0:7] DIV;
   input [7:0] PH_SEL;


   // Internal wires
   wire n_3;
   wire n_2;
   wire n_1;
   wire n172;
   wire n173;
   wire n175;
   wire n176;
   wire n177;
   wire n54;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n69;
   wire n84;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n99;
   wire n100;
   wire n101;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n163;
   wire n165;
   wire n166;
   wire n167;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire [0:7] PH_THRM;

   assign SEL_SIDE[29] = n56 ;
   assign SEL_SIDE[12] = n57 ;
   assign SEL_SIDE[4] = n177 ;

   // Module instantiations
   BUFTD3 I5_I3_3_ (
	.I(DIV[1]),
	.OE(PH_THRM[6]),
	.Z(CLK_B[1]));
   BUFTD3 I5_I3_2_ (
	.I(DIV[3]),
	.OE(PH_THRM[4]),
	.Z(CLK_B[1]));
   BUFTD3 I5_I3_1_ (
	.I(DIV[5]),
	.OE(PH_THRM[2]),
	.Z(CLK_B[1]));
   BUFTD3 I5_I3_0_ (
	.I(DIV[7]),
	.OE(PH_THRM[0]),
	.Z(CLK_B[1]));
   BUFTD3 I3_I2_7_ (
	.I(DIV[0]),
	.OE(PH_THRM[0]),
	.Z(CLK_A[2]));
   BUFTD3 I3_I2_6_ (
	.I(DIV[2]),
	.OE(PH_THRM[6]),
	.Z(CLK_A[2]));
   BUFTD3 I3_I2_5_ (
	.I(DIV[4]),
	.OE(PH_THRM[4]),
	.Z(CLK_A[2]));
   BUFTD3 I3_I2_4_ (
	.I(DIV[6]),
	.OE(PH_THRM[2]),
	.Z(CLK_A[2]));
   BUFTD3 I7_I2_7_ (
	.I(DIV[0]),
	.OE(PH_THRM[6]),
	.Z(CLK_A[0]));
   BUFTD3 I7_I2_6_ (
	.I(DIV[2]),
	.OE(PH_THRM[4]),
	.Z(CLK_A[0]));
   BUFTD3 I7_I2_5_ (
	.I(DIV[4]),
	.OE(PH_THRM[2]),
	.Z(CLK_A[0]));
   BUFTD3 I7_I2_4_ (
	.I(DIV[6]),
	.OE(PH_THRM[0]),
	.Z(CLK_A[0]));
   BUFTD3 I7_I3_1_ (
	.I(DIV[5]),
	.OE(PH_THRM[1]),
	.Z(CLK_B[0]));
   BUFTD3 I5_I2_4_ (
	.I(DIV[6]),
	.OE(PH_THRM[1]),
	.Z(CLK_A[1]));
   BUFTD3 I3_I3_0_ (
	.I(DIV[7]),
	.OE(PH_THRM[1]),
	.Z(CLK_B[2]));
   BUFTD3 I5_I2_7_ (
	.I(DIV[0]),
	.OE(PH_THRM[7]),
	.Z(CLK_A[1]));
   BUFTD3 I3_I3_3_ (
	.I(DIV[1]),
	.OE(PH_THRM[7]),
	.Z(CLK_B[2]));
   BUFTD3 I7_I3_0_ (
	.I(DIV[7]),
	.OE(PH_THRM[7]),
	.Z(CLK_B[0]));
   BUFTD3 I5_I2_6_ (
	.I(DIV[2]),
	.OE(PH_THRM[5]),
	.Z(CLK_A[1]));
   BUFTD3 I5_I2_5_ (
	.I(DIV[4]),
	.OE(n63),
	.Z(CLK_A[1]));
   BUFTD3 I3_I3_2_ (
	.I(DIV[3]),
	.OE(PH_THRM[5]),
	.Z(CLK_B[2]));
   BUFTD3 I3_I3_1_ (
	.I(DIV[5]),
	.OE(n63),
	.Z(CLK_B[2]));
   BUFTD3 I7_I3_2_ (
	.I(DIV[3]),
	.OE(n63),
	.Z(CLK_B[0]));
   BUFTD3 I7_I3_3_ (
	.I(DIV[1]),
	.OE(PH_THRM[5]),
	.Z(CLK_B[0]));
   XNR2D2 U121 (
	.A1(n128),
	.A2(SEL_SIDE[32]),
	.ZN(SEL[5]));
   XNR2D2 U122 (
	.A1(n108),
	.A2(PH_SEL[5]),
	.ZN(SEL_SIDE[21]));
   XNR2D2 U123 (
	.A1(n69),
	.A2(SEL_SIDE[32]),
	.ZN(SEL_SIDE[19]));
   OAI21D0 U124 (
	.A1(n132),
	.A2(n146),
	.B(n84),
	.ZN(n99));
   NR2XD0 U125 (
	.A1(n149),
	.A2(n129),
	.ZN(n100));
   NR2D1 U126 (
	.A1(n110),
	.A2(SEL_SIDE[32]),
	.ZN(n132));
   CKXOR2D1 U127 (
	.A1(n95),
	.A2(SEL_SIDE[32]),
	.Z(n61));
   INVD2 U128 (
	.I(SEL[5]),
	.ZN(SEL_SIDE[5]));
   NR2XD0 U129 (
	.A1(n94),
	.A2(n93),
	.ZN(n95));
   XNR2D1 U130 (
	.A1(n127),
	.A2(PH_SEL[5]),
	.ZN(n172));
   ND2D1 U131 (
	.A1(n127),
	.A2(n126),
	.ZN(n128));
   INVD1 U132 (
	.I(n64),
	.ZN(n69));
   ND2D1 U133 (
	.A1(n110),
	.A2(n109),
	.ZN(n127));
   ND2D1 U134 (
	.A1(n113),
	.A2(PH_SEL[5]),
	.ZN(n141));
   ND2D1 U135 (
	.A1(n152),
	.A2(PH_SEL[0]),
	.ZN(n89));
   INVD1 U136 (
	.I(n154),
	.ZN(n152));
   ND2D1 U137 (
	.A1(n161),
	.A2(PH_SEL[7]),
	.ZN(n166));
   NR2XD1 U138 (
	.A1(PH_SEL[7]),
	.A2(n161),
	.ZN(PH_THRM[4]));
   ND2D1 U139 (
	.A1(PH_SEL[6]),
	.A2(PH_SEL[7]),
	.ZN(n167));
   INVD2 U143 (
	.I(n172),
	.ZN(SEL_SIDE[6]));
   INVD1 U148 (
	.I(n97),
	.ZN(n135));
   ND2D0 U149 (
	.A1(n104),
	.A2(n160),
	.ZN(n106));
   ND2D0 U150 (
	.A1(n154),
	.A2(n116),
	.ZN(n88));
   ND3D0 U151 (
	.A1(n146),
	.A2(SEL_SIDE[32]),
	.A3(n121),
	.ZN(n138));
   OR2D0 U152 (
	.A1(PH_SEL[2]),
	.A2(PH_SEL[0]),
	.Z(n126));
   INVD0 U153 (
	.I(PH_SEL[4]),
	.ZN(n139));
   ND2D0 U154 (
	.A1(SEL_SIDE[32]),
	.A2(n139),
	.ZN(n159));
   INVD3 U158 (
	.I(SEL_SIDE[32]),
	.ZN(SEL[32]));
   INVD0 U159 (
	.I(n138),
	.ZN(n140));
   ND2D0 U160 (
	.A1(n110),
	.A2(SEL_SIDE[32]),
	.ZN(n133));
   ND2D0 U162 (
	.A1(n155),
	.A2(PH_SEL[5]),
	.ZN(n153));
   XNR2D0 U163 (
	.A1(n149),
	.A2(PH_SEL[5]),
	.ZN(n176));
   XNR2D0 U164 (
	.A1(n106),
	.A2(PH_SEL[5]),
	.ZN(n173));
   ND2D0 U165 (
	.A1(n107),
	.A2(n106),
	.ZN(n108));
   ND3D0 U166 (
	.A1(n139),
	.A2(n121),
	.A3(n105),
	.ZN(n107));
   OR2D0 U167 (
	.A1(n141),
	.A2(n139),
	.Z(n114));
   OA211D0 U168 (
	.A1(PH_SEL[3]),
	.A2(n138),
	.B(n112),
	.C(n159),
	.Z(n115));
   INVD2 U169 (
	.I(n59),
	.ZN(SEL_SIDE[11]));
   INVD2 U171 (
	.I(n62),
	.ZN(SEL_SIDE[8]));
   CKMUX2D0 U172 (
	.I0(PH_SEL[5]),
	.I1(n141),
	.S(n135),
	.Z(n137));
   INVD2 U173 (
	.I(n57),
	.ZN(SEL[12]));
   XNR2D0 U174 (
	.A1(n110),
	.A2(PH_SEL[5]),
	.ZN(n177));
   INVD2 U176 (
	.I(n176),
	.ZN(SEL_SIDE[28]));
   INVD2 U177 (
	.I(n173),
	.ZN(SEL_SIDE[22]));
   INVD2 U178 (
	.I(n177),
	.ZN(SEL[4]));
   AO21D0 U179 (
	.A1(n89),
	.A2(n155),
	.B(SEL_SIDE[32]),
	.Z(n54));
   OR2D2 U180 (
	.A1(n92),
	.A2(n144),
	.Z(SEL[17]));
   XOR2D1 U181 (
	.A1(n100),
	.A2(SEL_SIDE[32]),
	.Z(n56));
   XOR2D1 U182 (
	.A1(n101),
	.A2(SEL[32]),
	.Z(n57));
   XOR2D1 U183 (
	.A1(n120),
	.A2(SEL[32]),
	.Z(n58));
   XOR2D1 U184 (
	.A1(n103),
	.A2(SEL[32]),
	.Z(n59));
   XOR2D1 U185 (
	.A1(n94),
	.A2(SEL[32]),
	.Z(n60));
   XOR2D1 U186 (
	.A1(n97),
	.A2(SEL[32]),
	.Z(n62));
   MUX2ND1 U187 (
	.I0(n166),
	.I1(n165),
	.S(PH_SEL[5]),
	.ZN(n63));
   AO21D0 U188 (
	.A1(n146),
	.A2(n139),
	.B(n160),
	.Z(n64));
   ND2D0 U191 (
	.A1(PH_SEL[5]),
	.A2(PH_SEL[4]),
	.ZN(n158));
   ND2D0 U192 (
	.A1(n88),
	.A2(PH_SEL[4]),
	.ZN(n94));
   INVD2 U195 (
	.I(SEL[26]),
	.ZN(SEL_SIDE[26]));
   INVD2 U196 (
	.I(n61),
	.ZN(SEL_SIDE[9]));
   INVD2 U197 (
	.I(n56),
	.ZN(SEL[29]));
   INVD2 U198 (
	.I(n60),
	.ZN(SEL_SIDE[10]));
   INVD2 U199 (
	.I(n58),
	.ZN(SEL_SIDE[13]));
   INVD2 U201 (
	.I(SEL_SIDE[28]),
	.ZN(SEL[28]));
   INVD2 U202 (
	.I(SEL_SIDE[6]),
	.ZN(SEL[6]));
   INVD2 U203 (
	.I(SEL_SIDE[22]),
	.ZN(SEL[22]));
   MUX2ND1 U204 (
	.I0(n163),
	.I1(n165),
	.S(SEL_SIDE[32]),
	.ZN(PH_THRM[5]));
   INVD0 U205 (
	.I(PH_THRM[6]),
	.ZN(n163));
   MUX2ND1 U206 (
	.I0(n167),
	.I1(n163),
	.S(SEL_SIDE[32]),
	.ZN(PH_THRM[7]));
   INVD2 U208 (
	.I(SEL[14]),
	.ZN(SEL_SIDE[14]));
   INVD2 U209 (
	.I(SEL_SIDE[7]),
	.ZN(SEL[7]));
   INVD2 U210 (
	.I(SEL[18]),
	.ZN(SEL_SIDE[18]));
   AN2D2 U211 (
	.A1(n119),
	.A2(n153),
	.Z(SEL[18]));
   INVD2 U212 (
	.I(SEL[31]),
	.ZN(SEL_SIDE[31]));
   INVD2 U213 (
	.I(SEL[20]),
	.ZN(SEL_SIDE[20]));
   XNR2D2 U214 (
	.A1(SEL_SIDE[32]),
	.A2(n160),
	.ZN(SEL[20]));
   INVD2 U215 (
	.I(SEL_SIDE[16]),
	.ZN(SEL[16]));
   AN2D2 U216 (
	.A1(n159),
	.A2(n158),
	.Z(SEL_SIDE[16]));
   INVD2 U219 (
	.I(SEL_SIDE[21]),
	.ZN(SEL[21]));
   INVD2 U221 (
	.I(SEL_SIDE[24]),
	.ZN(SEL[24]));
   INVD2 U222 (
	.I(n175),
	.ZN(SEL_SIDE[24]));
   OAI21D1 U223 (
	.A1(n155),
	.A2(SEL_SIDE[32]),
	.B(n91),
	.ZN(n175));
   MUX2ND1 U224 (
	.I0(n167),
	.I1(n166),
	.S(SEL[32]),
	.ZN(PH_THRM[1]));
   ND2D1 U225 (
	.A1(n155),
	.A2(SEL_SIDE[32]),
	.ZN(n91));
   OR2D0 U226 (
	.A1(n148),
	.A2(SEL_SIDE[32]),
	.Z(n84));
   INVD0 U227 (
	.I(n146),
	.ZN(n148));
   INVD0 U228 (
	.I(PH_SEL[0]),
	.ZN(n105));
   INVD0 U230 (
	.I(PH_THRM[4]),
	.ZN(n165));
   ND2D0 U231 (
	.A1(n140),
	.A2(n139),
	.ZN(n143));
   ND2D1 U233 (
	.A1(PH_SEL[2]),
	.A2(PH_SEL[1]),
	.ZN(n154));
   NR2D2 U234 (
	.A1(PH_SEL[3]),
	.A2(PH_SEL[4]),
	.ZN(n155));
   INVD2 U236 (
	.I(SEL_SIDE[25]),
	.ZN(SEL[25]));
   INVD2 U237 (
	.I(SEL_SIDE[8]),
	.ZN(SEL[8]));
   INVD1 U240 (
	.I(PH_SEL[3]),
	.ZN(n116));
   INVD2 U241 (
	.I(SEL_SIDE[10]),
	.ZN(SEL[10]));
   ND2D0 U242 (
	.A1(PH_SEL[5]),
	.A2(PH_SEL[3]),
	.ZN(n90));
   MUX2ND0 U243 (
	.I0(n90),
	.I1(n159),
	.S(n89),
	.ZN(n92));
   ND2D1 U244 (
	.A1(n91),
	.A2(n158),
	.ZN(n144));
   INVD2 U245 (
	.I(SEL[17]),
	.ZN(SEL_SIDE[17]));
   NR2D0 U246 (
	.A1(PH_SEL[3]),
	.A2(PH_SEL[0]),
	.ZN(n93));
   INVD2 U248 (
	.I(SEL_SIDE[9]),
	.ZN(SEL[9]));
   INVD1 U249 (
	.I(PH_SEL[2]),
	.ZN(n121));
   ND2D2 U250 (
	.A1(n155),
	.A2(n121),
	.ZN(n149));
   NR2D1 U251 (
	.A1(n149),
	.A2(SEL_SIDE[32]),
	.ZN(n147));
   INVD1 U252 (
	.I(n147),
	.ZN(n123));
   NR2D1 U253 (
	.A1(n149),
	.A2(PH_SEL[1]),
	.ZN(n96));
   NR2D2 U255 (
	.A1(PH_SEL[0]),
	.A2(PH_SEL[1]),
	.ZN(n146));
   AOI21D1 U256 (
	.A1(PH_SEL[2]),
	.A2(PH_SEL[3]),
	.B(PH_SEL[4]),
	.ZN(n160));
   INVD2 U257 (
	.I(SEL_SIDE[19]),
	.ZN(SEL[19]));
   ND2D1 U258 (
	.A1(n135),
	.A2(PH_SEL[2]),
	.ZN(n110));
   AN2D2 U259 (
	.A1(n99),
	.A2(n133),
	.Z(SEL_SIDE[3]));
   INVD2 U260 (
	.I(SEL_SIDE[3]),
	.ZN(SEL[3]));
   AN2D0 U261 (
	.A1(PH_SEL[0]),
	.A2(PH_SEL[1]),
	.Z(n129));
   INVD2 U264 (
	.I(SEL_SIDE[11]),
	.ZN(SEL[11]));
   ND2D0 U266 (
	.A1(PH_SEL[3]),
	.A2(PH_SEL[1]),
	.ZN(n104));
   ND2D0 U267 (
	.A1(n135),
	.A2(PH_SEL[1]),
	.ZN(n109));
   ND2D0 U268 (
	.A1(n135),
	.A2(PH_SEL[5]),
	.ZN(n112));
   ND2D0 U269 (
	.A1(n146),
	.A2(n121),
	.ZN(n113));
   AN2D2 U270 (
	.A1(n115),
	.A2(n114),
	.Z(SEL_SIDE[15]));
   INVD2 U271 (
	.I(SEL_SIDE[15]),
	.ZN(SEL[15]));
   OA31D1 U275 (
	.A1(PH_SEL[1]),
	.A2(PH_SEL[2]),
	.A3(PH_SEL[3]),
	.B(PH_SEL[4]),
	.Z(n145));
   OAI21D1 U276 (
	.A1(n126),
	.A2(PH_SEL[3]),
	.B(n145),
	.ZN(n120));
   INVD2 U277 (
	.I(SEL_SIDE[13]),
	.ZN(SEL[13]));
   OAI21D0 U279 (
	.A1(n146),
	.A2(n121),
	.B(n155),
	.ZN(n122));
   ND2D1 U280 (
	.A1(n122),
	.A2(SEL_SIDE[32]),
	.ZN(n124));
   MUX2ND0 U282 (
	.I0(SEL_SIDE[32]),
	.I1(n132),
	.S(n129),
	.ZN(n130));
   AN2D2 U283 (
	.A1(n130),
	.A2(n133),
	.Z(SEL_SIDE[1]));
   INVD2 U284 (
	.I(SEL_SIDE[1]),
	.ZN(SEL[1]));
   MUX2ND0 U285 (
	.I0(SEL_SIDE[32]),
	.I1(n132),
	.S(PH_SEL[1]),
	.ZN(n134));
   AN2D2 U286 (
	.A1(n134),
	.A2(n133),
	.Z(SEL_SIDE[2]));
   INVD2 U287 (
	.I(SEL_SIDE[2]),
	.ZN(SEL[2]));
   AN2D2 U288 (
	.A1(n137),
	.A2(n138),
	.Z(SEL_SIDE[7]));
   IND2D0 U289 (
	.A1(n141),
	.B1(PH_SEL[3]),
	.ZN(n142));
   IAO22D2 U290 (
	.A1(SEL_SIDE[32]),
	.A2(n145),
	.B1(n145),
	.B2(SEL_SIDE[32]),
	.ZN(SEL[14]));
   ND2D0 U291 (
	.A1(n147),
	.A2(n146),
	.ZN(n151));
   OAI21D0 U292 (
	.A1(n149),
	.A2(n148),
	.B(SEL_SIDE[32]),
	.ZN(n150));
   AN2D2 U293 (
	.A1(n151),
	.A2(n150),
	.Z(SEL[31]));
   INVD2 U295 (
	.I(SEL[30]),
	.ZN(SEL_SIDE[30]));
   INVD2 U296 (
	.I(SEL_SIDE[27]),
	.ZN(SEL[27]));
   INVD2 U297 (
	.I(SEL[23]),
	.ZN(SEL_SIDE[23]));
   INVD1 U298 (
	.I(n167),
	.ZN(PH_THRM[0]));
   INVD1 U299 (
	.I(n166),
	.ZN(PH_THRM[2]));
   CKND1 U145 (
	.CLK(PH_SEL[5]),
	.CN(SEL_SIDE[32]));
   OAI21D0 U140 (
	.A1(SEL[32]),
	.A2(n179),
	.B(n178),
	.ZN(n119));
   IOA21D0 U141 (
	.A1(n154),
	.A2(n139),
	.B(SEL[32]),
	.ZN(n178));
   OAI21D0 U144 (
	.A1(n154),
	.A2(n116),
	.B(n139),
	.ZN(n179));
   OR2D0 U147 (
	.A1(n153),
	.A2(n152),
	.Z(n184));
   IOA21D0 U156 (
	.A1(n116),
	.A2(n146),
	.B(n101),
	.ZN(n103));
   IOA21D0 U170 (
	.A1(PH_SEL[4]),
	.A2(PH_SEL[2]),
	.B(n97),
	.ZN(n101));
   OR2D1 U175 (
	.A1(n153),
	.A2(n148),
	.Z(n180));
   CKND2D0 U190 (
	.A1(PH_SEL[4]),
	.A2(PH_SEL[3]),
	.ZN(n97));
   INVD2 U217 (
	.I(n181),
	.ZN(SEL_SIDE[25]));
   IOA21D0 U218 (
	.A1(n182),
	.A2(n89),
	.B(n54),
	.ZN(n181));
   ND3D3 U220 (
	.A1(n180),
	.A2(n124),
	.A3(n123),
	.ZN(SEL_SIDE[27]));
   INVD0 U229 (
	.I(n91),
	.ZN(n182));
   INVD0 U235 (
	.I(PH_SEL[1]),
	.ZN(n183));
   IAO22D2 U238 (
	.A1(PH_SEL[5]),
	.A2(n96),
	.B1(n147),
	.B2(n183),
	.ZN(SEL[30]));
   AN2D2 U254 (
	.A1(n184),
	.A2(n185),
	.Z(SEL[26]));
   AO21D0 U263 (
	.A1(n155),
	.A2(n154),
	.B(PH_SEL[5]),
	.Z(n185));
   IND3D0 U272 (
	.A1(n144),
	.B1(n142),
	.B2(n143),
	.ZN(SEL[23]));
   CKND0 U273 (
	.CLK(PH_SEL[6]),
	.CN(n161));
   NR2XD1 U274 (
	.A1(PH_SEL[7]),
	.A2(PH_SEL[6]),
	.ZN(PH_THRM[6]));
endmodule

