
// Generated by Cadence Genus(TM) Synthesis Solution 16.11-s015_1
// Generated on: Aug 23 2018 18:12:00 EDT (Aug 23 2018 22:12:00 UTC)

// Verification Directory fv/spi_slave 

module syn_spi_slave(rst, spi_ssel_i, spi_sck_i, spi_mosi_i, spi_miso_o,
     clk_i, do_valid_o, do_o);
  input rst, spi_ssel_i, spi_sck_i, spi_mosi_i, clk_i;
  output spi_miso_o, do_valid_o;
  output [23:0] do_o;
  wire rst, spi_ssel_i, spi_sck_i, spi_mosi_i, clk_i;
  wire spi_miso_o, do_valid_o;
  wire [23:0] do_o;
  wire [23:0] sh_reg;
  wire [23:0] di_reg;
  wire [4:0] state_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, do_transfer_reg;
  wire do_valid_A, do_valid_B, do_valid_C, do_valid_D, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, preload_miso,
       tx_bit_reg;
  wire wr_ack_reg, wren;
  SDFFSX1 wren_reg(.SN (n_186), .CK (clk_i), .D (n_115), .SI (wren),
       .SE (n_135), .Q (wren), .QN (UNCONNECTED));
  DFFSX1 \sh_reg_reg[23] (.SN (n_186), .CK (spi_sck_i), .D (n_174), .Q
       (UNCONNECTED0), .QN (sh_reg[23]));
  DFFSX2 \sh_reg_reg[11] (.SN (n_186), .CK (spi_sck_i), .D (n_179), .Q
       (UNCONNECTED1), .QN (sh_reg[11]));
  DFFSX2 \sh_reg_reg[8] (.SN (n_186), .CK (spi_sck_i), .D (n_185), .Q
       (UNCONNECTED2), .QN (sh_reg[8]));
  DFFSX2 \di_reg_reg[23] (.SN (n_186), .CK (clk_i), .D (n_180), .Q
       (UNCONNECTED3), .QN (di_reg[23]));
  DFFSX2 \sh_reg_reg[1] (.SN (n_186), .CK (spi_sck_i), .D (n_182), .Q
       (UNCONNECTED4), .QN (sh_reg[1]));
  DFFSX2 \sh_reg_reg[18] (.SN (n_186), .CK (spi_sck_i), .D (n_176), .Q
       (UNCONNECTED5), .QN (sh_reg[18]));
  DFFSX2 \sh_reg_reg[20] (.SN (n_186), .CK (spi_sck_i), .D (n_175), .Q
       (UNCONNECTED6), .QN (sh_reg[20]));
  DFFSX2 \sh_reg_reg[13] (.SN (n_186), .CK (spi_sck_i), .D (n_184), .Q
       (UNCONNECTED7), .QN (sh_reg[13]));
  DFFSX2 \sh_reg_reg[10] (.SN (n_186), .CK (spi_sck_i), .D (n_181), .Q
       (UNCONNECTED8), .QN (sh_reg[10]));
  DFFSX2 \sh_reg_reg[15] (.SN (n_186), .CK (spi_sck_i), .D (n_178), .Q
       (UNCONNECTED9), .QN (sh_reg[15]));
  DFFSX2 \sh_reg_reg[9] (.SN (n_186), .CK (spi_sck_i), .D (n_183), .Q
       (UNCONNECTED10), .QN (sh_reg[9]));
  DFFSX2 \sh_reg_reg[17] (.SN (n_186), .CK (spi_sck_i), .D (n_177), .Q
       (UNCONNECTED11), .QN (sh_reg[17]));
  DFFNSX2 tx_bit_reg_reg(.SN (n_186), .CKN (spi_sck_i), .D (n_164), .Q
       (UNCONNECTED12), .QN (tx_bit_reg));
  DFFSX2 do_transfer_reg_reg(.SN (n_186), .CK (spi_sck_i), .D (n_165),
       .Q (UNCONNECTED13), .QN (do_transfer_reg));
  DFFSX1 \di_reg_reg[0] (.SN (n_186), .CK (clk_i), .D (n_167), .Q
       (di_reg[0]), .QN (UNCONNECTED14));
  DFFSX1 \di_reg_reg[5] (.SN (n_186), .CK (clk_i), .D (n_138), .Q
       (di_reg[5]), .QN (UNCONNECTED15));
  DFFSX1 \di_reg_reg[17] (.SN (n_186), .CK (clk_i), .D (n_152), .Q
       (di_reg[17]), .QN (UNCONNECTED16));
  DFFSX1 \di_reg_reg[18] (.SN (n_186), .CK (clk_i), .D (n_139), .Q
       (di_reg[18]), .QN (UNCONNECTED17));
  DFFSX1 \di_reg_reg[19] (.SN (n_186), .CK (clk_i), .D (n_137), .Q
       (di_reg[19]), .QN (UNCONNECTED18));
  DFFSX1 \di_reg_reg[20] (.SN (n_186), .CK (clk_i), .D (n_163), .Q
       (di_reg[20]), .QN (UNCONNECTED19));
  DFFSX1 \di_reg_reg[6] (.SN (n_186), .CK (clk_i), .D (n_136), .Q
       (di_reg[6]), .QN (UNCONNECTED20));
  DFFSX1 \di_reg_reg[21] (.SN (n_186), .CK (clk_i), .D (n_170), .Q
       (di_reg[21]), .QN (UNCONNECTED21));
  DFFSX1 \di_reg_reg[7] (.SN (n_186), .CK (clk_i), .D (n_169), .Q
       (di_reg[7]), .QN (UNCONNECTED22));
  DFFSX1 \di_reg_reg[22] (.SN (n_186), .CK (clk_i), .D (n_168), .Q
       (di_reg[22]), .QN (UNCONNECTED23));
  DFFSX1 \di_reg_reg[10] (.SN (n_186), .CK (clk_i), .D (n_162), .Q
       (di_reg[10]), .QN (UNCONNECTED24));
  DFFSX1 \di_reg_reg[8] (.SN (n_186), .CK (clk_i), .D (n_166), .Q
       (di_reg[8]), .QN (UNCONNECTED25));
  DFFSX1 \di_reg_reg[9] (.SN (n_186), .CK (clk_i), .D (n_173), .Q
       (di_reg[9]), .QN (UNCONNECTED26));
  DFFSX1 \di_reg_reg[14] (.SN (n_186), .CK (clk_i), .D (n_156), .Q
       (di_reg[14]), .QN (UNCONNECTED27));
  DFFSX1 \di_reg_reg[11] (.SN (n_186), .CK (clk_i), .D (n_161), .Q
       (di_reg[11]), .QN (UNCONNECTED28));
  DFFSX2 \sh_reg_reg[14] (.SN (n_186), .CK (spi_sck_i), .D (n_154), .Q
       (UNCONNECTED29), .QN (sh_reg[14]));
  DFFSX1 \di_reg_reg[3] (.SN (n_186), .CK (clk_i), .D (n_158), .Q
       (di_reg[3]), .QN (UNCONNECTED30));
  DFFSX1 \di_reg_reg[2] (.SN (n_186), .CK (clk_i), .D (n_157), .Q
       (di_reg[2]), .QN (UNCONNECTED31));
  DFFSX1 \di_reg_reg[15] (.SN (n_186), .CK (clk_i), .D (n_145), .Q
       (di_reg[15]), .QN (UNCONNECTED32));
  DFFSX1 \di_reg_reg[13] (.SN (n_186), .CK (clk_i), .D (n_159), .Q
       (di_reg[13]), .QN (UNCONNECTED33));
  DFFSX1 \di_reg_reg[1] (.SN (n_186), .CK (clk_i), .D (n_153), .Q
       (di_reg[1]), .QN (UNCONNECTED34));
  DFFSX1 \di_reg_reg[16] (.SN (n_186), .CK (clk_i), .D (n_151), .Q
       (di_reg[16]), .QN (UNCONNECTED35));
  DFFSX1 \di_reg_reg[4] (.SN (n_186), .CK (clk_i), .D (n_155), .Q
       (di_reg[4]), .QN (UNCONNECTED36));
  DFFSX1 \di_reg_reg[12] (.SN (n_186), .CK (clk_i), .D (n_160), .Q
       (di_reg[12]), .QN (UNCONNECTED37));
  DFFSX2 \sh_reg_reg[2] (.SN (n_186), .CK (spi_sck_i), .D (n_148), .Q
       (UNCONNECTED38), .QN (sh_reg[2]));
  DFFSX2 \sh_reg_reg[3] (.SN (n_186), .CK (spi_sck_i), .D (n_147), .Q
       (UNCONNECTED39), .QN (sh_reg[3]));
  DFFSX2 \sh_reg_reg[4] (.SN (n_186), .CK (spi_sck_i), .D (n_146), .Q
       (UNCONNECTED40), .QN (sh_reg[4]));
  DFFSX2 \sh_reg_reg[5] (.SN (n_186), .CK (spi_sck_i), .D (n_150), .Q
       (UNCONNECTED41), .QN (sh_reg[5]));
  DFFSX2 \sh_reg_reg[6] (.SN (n_186), .CK (spi_sck_i), .D (n_144), .Q
       (UNCONNECTED42), .QN (sh_reg[6]));
  DFFSX2 \sh_reg_reg[7] (.SN (n_186), .CK (spi_sck_i), .D (n_143), .Q
       (UNCONNECTED43), .QN (sh_reg[7]));
  DFFSX2 \sh_reg_reg[12] (.SN (n_186), .CK (spi_sck_i), .D (n_142), .Q
       (UNCONNECTED44), .QN (sh_reg[12]));
  DFFSX2 \sh_reg_reg[16] (.SN (n_186), .CK (spi_sck_i), .D (n_149), .Q
       (UNCONNECTED45), .QN (sh_reg[16]));
  DFFSX2 \sh_reg_reg[19] (.SN (n_186), .CK (spi_sck_i), .D (n_171), .Q
       (UNCONNECTED46), .QN (sh_reg[19]));
  DFFSX2 \sh_reg_reg[21] (.SN (n_186), .CK (spi_sck_i), .D (n_140), .Q
       (UNCONNECTED47), .QN (sh_reg[21]));
  DFFSX2 \sh_reg_reg[22] (.SN (n_186), .CK (spi_sck_i), .D (n_141), .Q
       (UNCONNECTED48), .QN (sh_reg[22]));
  AND2X1 g3347(.A (n_130), .B (n_58), .Y (n_185));
  AND2X1 g3345(.A (n_126), .B (n_44), .Y (n_184));
  AND2X1 g3348(.A (n_129), .B (n_61), .Y (n_183));
  AND2X1 g3346(.A (n_132), .B (n_59), .Y (n_182));
  AND2X1 g3349(.A (n_128), .B (n_56), .Y (n_181));
  MXI2X2 g3379(.A (do_o[23]), .B (di_reg[23]), .S0 (n_120), .Y (n_180));
  AND2X1 g3350(.A (n_127), .B (n_55), .Y (n_179));
  AND2X1 g3352(.A (n_125), .B (n_52), .Y (n_178));
  AND2X1 g3353(.A (n_124), .B (n_51), .Y (n_177));
  AND2X1 g3354(.A (n_123), .B (n_54), .Y (n_176));
  AND2X1 g3355(.A (n_122), .B (n_60), .Y (n_175));
  AND2X1 g3356(.A (n_134), .B (n_50), .Y (n_174));
  AOI2BB2X2 g3382(.A0N (do_valid_o), .A1N (di_reg[9]), .B0
       (do_valid_o), .B1 (do_o[9]), .Y (n_173));
  AND2X1 g3420(.A (n_114), .B (n_91), .Y (n_171));
  AOI2BB2X2 g3375(.A0N (do_valid_o), .A1N (di_reg[21]), .B0
       (do_valid_o), .B1 (do_o[21]), .Y (n_170));
  AOI2BB2X2 g3376(.A0N (do_valid_o), .A1N (di_reg[7]), .B0
       (do_valid_o), .B1 (do_o[7]), .Y (n_169));
  AOI2BB2X2 g3377(.A0N (do_valid_o), .A1N (di_reg[22]), .B0
       (do_valid_o), .B1 (do_o[22]), .Y (n_168));
  AOI2BB2X2 g3378(.A0N (do_valid_o), .A1N (di_reg[0]), .B0
       (do_valid_o), .B1 (do_o[0]), .Y (n_167));
  AOI2BB2X2 g3380(.A0N (do_valid_o), .A1N (di_reg[8]), .B0
       (do_valid_o), .B1 (do_o[8]), .Y (n_166));
  NOR2X1 g3351(.A (n_107), .B (n_87), .Y (n_165));
  AOI222X4 g3381(.A0 (n_103), .A1 (tx_bit_reg), .B0 (n_133), .B1
       (sh_reg[23]), .C0 (n_100), .C1 (di_reg[23]), .Y (n_164));
  AOI2BB2X2 g3374(.A0N (do_valid_o), .A1N (di_reg[20]), .B0
       (do_valid_o), .B1 (do_o[20]), .Y (n_163));
  AOI2BB2X2 g3383(.A0N (do_valid_o), .A1N (di_reg[10]), .B0
       (do_valid_o), .B1 (do_o[10]), .Y (n_162));
  AOI2BB2X2 g3384(.A0N (do_valid_o), .A1N (di_reg[11]), .B0
       (do_valid_o), .B1 (do_o[11]), .Y (n_161));
  AOI2BB2X2 g3385(.A0N (do_valid_o), .A1N (di_reg[12]), .B0
       (do_valid_o), .B1 (do_o[12]), .Y (n_160));
  AOI2BB2X2 g3386(.A0N (do_valid_o), .A1N (di_reg[13]), .B0
       (do_valid_o), .B1 (do_o[13]), .Y (n_159));
  AOI2BB2X2 g3387(.A0N (do_valid_o), .A1N (di_reg[3]), .B0
       (do_valid_o), .B1 (do_o[3]), .Y (n_158));
  AOI2BB2X2 g3388(.A0N (do_valid_o), .A1N (di_reg[2]), .B0
       (do_valid_o), .B1 (do_o[2]), .Y (n_157));
  AOI2BB2X2 g3389(.A0N (do_valid_o), .A1N (di_reg[14]), .B0
       (do_valid_o), .B1 (do_o[14]), .Y (n_156));
  AOI2BB2X2 g3390(.A0N (do_valid_o), .A1N (di_reg[4]), .B0
       (do_valid_o), .B1 (do_o[4]), .Y (n_155));
  AND2X1 g3400(.A (n_112), .B (n_104), .Y (n_154));
  AOI2BB2X2 g3369(.A0N (do_valid_o), .A1N (di_reg[1]), .B0
       (do_valid_o), .B1 (do_o[1]), .Y (n_153));
  AOI2BB2X2 g3393(.A0N (do_valid_o), .A1N (di_reg[17]), .B0
       (do_valid_o), .B1 (do_o[17]), .Y (n_152));
  AOI2BB2X2 g3392(.A0N (do_valid_o), .A1N (di_reg[16]), .B0
       (do_valid_o), .B1 (do_o[16]), .Y (n_151));
  AND2X1 g3394(.A (n_116), .B (n_97), .Y (n_150));
  AND2X1 g3395(.A (n_111), .B (n_92), .Y (n_149));
  AND2X1 g3397(.A (n_119), .B (n_102), .Y (n_148));
  AND2X1 g3398(.A (n_118), .B (n_96), .Y (n_147));
  AND2X1 g3399(.A (n_117), .B (n_94), .Y (n_146));
  AOI2BB2X2 g3391(.A0N (do_valid_o), .A1N (di_reg[15]), .B0
       (do_valid_o), .B1 (do_o[15]), .Y (n_145));
  AND2X1 g3401(.A (n_121), .B (n_93), .Y (n_144));
  AND2X1 g3402(.A (n_110), .B (n_99), .Y (n_143));
  AND2X1 g3403(.A (n_113), .B (n_95), .Y (n_142));
  AND2X1 g3409(.A (n_108), .B (n_89), .Y (n_141));
  AND2X1 g3408(.A (n_109), .B (n_90), .Y (n_140));
  AOI2BB2X2 g3370(.A0N (do_valid_o), .A1N (di_reg[18]), .B0
       (do_valid_o), .B1 (do_o[18]), .Y (n_139));
  AOI2BB2X2 g3371(.A0N (do_valid_o), .A1N (di_reg[5]), .B0
       (do_valid_o), .B1 (do_o[5]), .Y (n_138));
  AOI2BB2X2 g3372(.A0N (do_valid_o), .A1N (di_reg[19]), .B0
       (do_valid_o), .B1 (do_o[19]), .Y (n_137));
  AOI2BB2X2 g3373(.A0N (do_valid_o), .A1N (di_reg[6]), .B0
       (do_valid_o), .B1 (do_o[6]), .Y (n_136));
  NOR2X2 g3405(.A (do_valid_o), .B (wr_ack_reg), .Y (n_135));
  AOI2BB2X2 g3407(.A0N (n_131), .A1N (di_reg[22]), .B0 (n_133), .B1
       (sh_reg[22]), .Y (n_134));
  AOI2BB2X2 g3410(.A0N (n_131), .A1N (di_reg[0]), .B0 (n_133), .B1
       (sh_reg[0]), .Y (n_132));
  AOI2BB2X2 g3411(.A0N (n_131), .A1N (di_reg[7]), .B0 (n_133), .B1
       (sh_reg[7]), .Y (n_130));
  AOI2BB2X2 g3412(.A0N (n_131), .A1N (di_reg[8]), .B0 (n_133), .B1
       (sh_reg[8]), .Y (n_129));
  AOI2BB2X2 g3413(.A0N (n_131), .A1N (di_reg[9]), .B0 (n_133), .B1
       (sh_reg[9]), .Y (n_128));
  AOI2BB2X2 g3414(.A0N (n_131), .A1N (di_reg[10]), .B0 (n_133), .B1
       (sh_reg[10]), .Y (n_127));
  AOI2BB2X2 g3415(.A0N (n_131), .A1N (di_reg[12]), .B0 (n_133), .B1
       (sh_reg[12]), .Y (n_126));
  AOI2BB2X2 g3416(.A0N (n_131), .A1N (di_reg[14]), .B0 (n_133), .B1
       (sh_reg[14]), .Y (n_125));
  AOI2BB2X2 g3417(.A0N (n_131), .A1N (di_reg[16]), .B0 (n_133), .B1
       (sh_reg[16]), .Y (n_124));
  AOI2BB2X2 g3418(.A0N (n_131), .A1N (di_reg[17]), .B0 (n_133), .B1
       (sh_reg[17]), .Y (n_123));
  AOI2BB2X2 g3419(.A0N (n_131), .A1N (di_reg[19]), .B0 (n_133), .B1
       (sh_reg[19]), .Y (n_122));
  NAND2XL g3454(.A (n_133), .B (sh_reg[5]), .Y (n_121));
  INVX1 g3422(.A (do_valid_o), .Y (n_120));
  NAND2XL g3450(.A (n_133), .B (sh_reg[1]), .Y (n_119));
  NAND2XL g3451(.A (n_133), .B (sh_reg[2]), .Y (n_118));
  NAND2XL g3452(.A (n_133), .B (sh_reg[3]), .Y (n_117));
  NAND2XL g3453(.A (n_133), .B (sh_reg[4]), .Y (n_116));
  INVXL g3421(.A (do_valid_o), .Y (n_115));
  NAND2XL g3459(.A (n_133), .B (sh_reg[18]), .Y (n_114));
  NAND2XL g3456(.A (n_133), .B (sh_reg[11]), .Y (n_113));
  NAND2XL g3457(.A (n_133), .B (sh_reg[13]), .Y (n_112));
  NAND2XL g3458(.A (n_133), .B (sh_reg[15]), .Y (n_111));
  NAND2XL g3455(.A (n_133), .B (sh_reg[6]), .Y (n_110));
  NAND2XL g3460(.A (n_133), .B (sh_reg[20]), .Y (n_109));
  NAND2XL g3461(.A (n_133), .B (sh_reg[21]), .Y (n_108));
  OAI2BB1X1 g3396(.A0N (n_41), .A1N (n_14), .B0 (n_106), .Y (n_107));
  DFFSX2 wr_ack_reg_reg(.SN (n_186), .CK (spi_sck_i), .D (n_101), .Q
       (UNCONNECTED49), .QN (wr_ack_reg));
  DFFSX4 \do_buffer_reg_reg[9] (.SN (n_186), .CK (spi_sck_i), .D
       (n_69), .Q (UNCONNECTED50), .QN (do_o[9]));
  DFFSX4 \do_buffer_reg_reg[13] (.SN (n_186), .CK (spi_sck_i), .D
       (n_68), .Q (UNCONNECTED51), .QN (do_o[13]));
  DFFSX4 \do_buffer_reg_reg[23] (.SN (n_186), .CK (spi_sck_i), .D
       (n_78), .Q (UNCONNECTED52), .QN (do_o[23]));
  DFFSX4 \do_buffer_reg_reg[16] (.SN (n_186), .CK (spi_sck_i), .D
       (n_82), .Q (UNCONNECTED53), .QN (do_o[16]));
  DFFSX4 \do_buffer_reg_reg[1] (.SN (n_186), .CK (spi_sck_i), .D
       (n_74), .Q (UNCONNECTED54), .QN (do_o[1]));
  DFFSX4 \do_buffer_reg_reg[17] (.SN (n_186), .CK (spi_sck_i), .D
       (n_77), .Q (UNCONNECTED55), .QN (do_o[17]));
  DFFSX4 \do_buffer_reg_reg[20] (.SN (n_186), .CK (spi_sck_i), .D
       (n_81), .Q (UNCONNECTED56), .QN (do_o[20]));
  DFFSX4 \do_buffer_reg_reg[18] (.SN (n_186), .CK (spi_sck_i), .D
       (n_84), .Q (UNCONNECTED57), .QN (do_o[18]));
  DFFSX4 \do_buffer_reg_reg[15] (.SN (n_186), .CK (spi_sck_i), .D
       (n_64), .Q (UNCONNECTED58), .QN (do_o[15]));
  DFFSX4 \do_buffer_reg_reg[19] (.SN (n_186), .CK (spi_sck_i), .D
       (n_88), .Q (UNCONNECTED59), .QN (do_o[19]));
  DFFSX2 \sh_reg_reg[0] (.SN (n_186), .CK (spi_sck_i), .D (n_98), .Q
       (UNCONNECTED60), .QN (sh_reg[0]));
  DFFSX4 \do_buffer_reg_reg[5] (.SN (n_186), .CK (spi_sck_i), .D
       (n_70), .Q (UNCONNECTED61), .QN (do_o[5]));
  CLKBUFX20 g3449(.A (n_187), .Y (do_valid_o));
  DFFSX4 \do_buffer_reg_reg[22] (.SN (n_186), .CK (spi_sck_i), .D
       (n_79), .Q (UNCONNECTED62), .QN (do_o[22]));
  DFFSX4 \do_buffer_reg_reg[0] (.SN (n_186), .CK (spi_sck_i), .D
       (n_75), .Q (UNCONNECTED63), .QN (do_o[0]));
  DFFSX4 \do_buffer_reg_reg[2] (.SN (n_186), .CK (spi_sck_i), .D
       (n_66), .Q (UNCONNECTED64), .QN (do_o[2]));
  DFFSX4 \do_buffer_reg_reg[3] (.SN (n_186), .CK (spi_sck_i), .D
       (n_72), .Q (UNCONNECTED65), .QN (do_o[3]));
  DFFSX4 \do_buffer_reg_reg[4] (.SN (n_186), .CK (spi_sck_i), .D
       (n_71), .Q (UNCONNECTED66), .QN (do_o[4]));
  DFFSX4 \do_buffer_reg_reg[6] (.SN (n_186), .CK (spi_sck_i), .D
       (n_62), .Q (UNCONNECTED67), .QN (do_o[6]));
  DFFSX4 \do_buffer_reg_reg[7] (.SN (n_186), .CK (spi_sck_i), .D
       (n_73), .Q (UNCONNECTED68), .QN (do_o[7]));
  DFFSX4 \do_buffer_reg_reg[8] (.SN (n_186), .CK (spi_sck_i), .D
       (n_67), .Q (UNCONNECTED69), .QN (do_o[8]));
  DFFSX4 \do_buffer_reg_reg[10] (.SN (n_186), .CK (spi_sck_i), .D
       (n_65), .Q (UNCONNECTED70), .QN (do_o[10]));
  DFFSX4 \do_buffer_reg_reg[11] (.SN (n_186), .CK (spi_sck_i), .D
       (n_76), .Q (UNCONNECTED71), .QN (do_o[11]));
  DFFSX4 \do_buffer_reg_reg[12] (.SN (n_186), .CK (spi_sck_i), .D
       (n_86), .Q (UNCONNECTED72), .QN (do_o[12]));
  DFFSX4 \do_buffer_reg_reg[14] (.SN (n_186), .CK (spi_sck_i), .D
       (n_63), .Q (UNCONNECTED73), .QN (do_o[14]));
  DFFSX4 \do_buffer_reg_reg[21] (.SN (n_186), .CK (spi_sck_i), .D
       (n_80), .Q (UNCONNECTED74), .QN (do_o[21]));
  DFFSX2 \state_reg_reg[4] (.SN (n_105), .CK (spi_sck_i), .D (n_83), .Q
       (UNCONNECTED75), .QN (state_reg[4]));
  DFFSX2 do_valid_o_reg_reg(.SN (n_186), .CK (clk_i), .D (n_57), .Q
       (UNCONNECTED76), .QN (n_187));
  OAI2BB1X1 g3462(.A0N (n_38), .A1N (n_43), .B0 (do_transfer_reg), .Y
       (n_106));
  DFFSX4 \state_reg_reg[2] (.SN (n_105), .CK (spi_sck_i), .D (n_47), .Q
       (UNCONNECTED77), .QN (state_reg[2]));
  DFFSX2 \state_reg_reg[1] (.SN (n_105), .CK (spi_sck_i), .D (n_45), .Q
       (UNCONNECTED78), .QN (state_reg[1]));
  DFFSX4 \state_reg_reg[0] (.SN (n_105), .CK (spi_sck_i), .D (n_49), .Q
       (UNCONNECTED79), .QN (state_reg[0]));
  DFFSX4 \state_reg_reg[3] (.SN (n_105), .CK (spi_sck_i), .D (n_53), .Q
       (state_reg[3]), .QN (UNCONNECTED80));
  OR2X4 g3497(.A (n_48), .B (n_16), .Y (n_133));
  AOI2BB2X2 g3472(.A0N (n_131), .A1N (di_reg[13]), .B0 (n_103), .B1
       (sh_reg[14]), .Y (n_104));
  AOI2BB2X2 g3465(.A0N (n_131), .A1N (di_reg[1]), .B0 (n_103), .B1
       (sh_reg[2]), .Y (n_102));
  AOI21X1 g3463(.A0 (n_103), .A1 (wr_ack_reg), .B0 (n_100), .Y (n_101));
  AOI2BB2X2 g3470(.A0N (n_131), .A1N (di_reg[6]), .B0 (n_103), .B1
       (sh_reg[7]), .Y (n_99));
  AOI32X4 g3464(.A0 (n_30), .A1 (spi_mosi_i), .A2 (n_186), .B0 (n_103),
       .B1 (sh_reg[0]), .Y (n_98));
  AOI2BB2X2 g3468(.A0N (n_131), .A1N (di_reg[4]), .B0 (n_103), .B1
       (sh_reg[5]), .Y (n_97));
  AOI2BB2X2 g3466(.A0N (n_131), .A1N (di_reg[2]), .B0 (n_103), .B1
       (sh_reg[3]), .Y (n_96));
  AOI2BB2X2 g3471(.A0N (n_131), .A1N (di_reg[11]), .B0 (n_103), .B1
       (sh_reg[12]), .Y (n_95));
  AOI2BB2X2 g3467(.A0N (n_131), .A1N (di_reg[3]), .B0 (n_103), .B1
       (sh_reg[4]), .Y (n_94));
  AOI2BB2X2 g3469(.A0N (n_131), .A1N (di_reg[5]), .B0 (n_103), .B1
       (sh_reg[6]), .Y (n_93));
  AOI2BB2X2 g3473(.A0N (n_131), .A1N (di_reg[15]), .B0 (n_103), .B1
       (sh_reg[16]), .Y (n_92));
  AOI2BB2X2 g3474(.A0N (n_131), .A1N (di_reg[18]), .B0 (n_103), .B1
       (sh_reg[19]), .Y (n_91));
  AOI2BB2X2 g3475(.A0N (n_131), .A1N (di_reg[20]), .B0 (n_103), .B1
       (sh_reg[21]), .Y (n_90));
  AOI2BB2X2 g3476(.A0N (n_131), .A1N (di_reg[21]), .B0 (n_103), .B1
       (sh_reg[22]), .Y (n_89));
  AOI22X2 g3477(.A0 (n_87), .A1 (sh_reg[18]), .B0 (n_85), .B1
       (do_o[19]), .Y (n_88));
  AOI22X2 g3478(.A0 (n_87), .A1 (sh_reg[11]), .B0 (n_85), .B1
       (do_o[12]), .Y (n_86));
  AOI22X2 g3479(.A0 (n_87), .A1 (sh_reg[17]), .B0 (n_85), .B1
       (do_o[18]), .Y (n_84));
  AND2X1 g3492(.A (n_40), .B (n_42), .Y (n_83));
  AOI22X2 g3498(.A0 (n_87), .A1 (sh_reg[15]), .B0 (n_85), .B1
       (do_o[16]), .Y (n_82));
  AOI22X2 g3499(.A0 (n_87), .A1 (sh_reg[19]), .B0 (n_85), .B1
       (do_o[20]), .Y (n_81));
  AOI22X2 g3500(.A0 (n_87), .A1 (sh_reg[20]), .B0 (n_85), .B1
       (do_o[21]), .Y (n_80));
  AOI22X2 g3501(.A0 (n_87), .A1 (sh_reg[21]), .B0 (n_85), .B1
       (do_o[22]), .Y (n_79));
  AOI22X2 g3502(.A0 (n_87), .A1 (sh_reg[22]), .B0 (n_85), .B1
       (do_o[23]), .Y (n_78));
  AOI22X2 g3503(.A0 (n_87), .A1 (sh_reg[16]), .B0 (n_85), .B1
       (do_o[17]), .Y (n_77));
  AOI22X2 g3504(.A0 (n_87), .A1 (sh_reg[10]), .B0 (n_85), .B1
       (do_o[11]), .Y (n_76));
  AOI22X2 g3505(.A0 (n_87), .A1 (spi_mosi_i), .B0 (n_85), .B1
       (do_o[0]), .Y (n_75));
  AOI22X2 g3506(.A0 (n_87), .A1 (sh_reg[0]), .B0 (n_85), .B1 (do_o[1]),
       .Y (n_74));
  AOI22X2 g3507(.A0 (n_87), .A1 (sh_reg[6]), .B0 (n_85), .B1 (do_o[7]),
       .Y (n_73));
  AOI22X2 g3508(.A0 (n_87), .A1 (sh_reg[2]), .B0 (n_85), .B1 (do_o[3]),
       .Y (n_72));
  AOI22X2 g3509(.A0 (n_87), .A1 (sh_reg[3]), .B0 (n_85), .B1 (do_o[4]),
       .Y (n_71));
  AOI22X2 g3510(.A0 (n_87), .A1 (sh_reg[4]), .B0 (n_85), .B1 (do_o[5]),
       .Y (n_70));
  AOI22X2 g3511(.A0 (n_87), .A1 (sh_reg[8]), .B0 (n_85), .B1 (do_o[9]),
       .Y (n_69));
  AOI22X2 g3512(.A0 (n_87), .A1 (sh_reg[12]), .B0 (n_85), .B1
       (do_o[13]), .Y (n_68));
  AOI22X2 g3513(.A0 (n_87), .A1 (sh_reg[7]), .B0 (n_85), .B1 (do_o[8]),
       .Y (n_67));
  AOI22X2 g3514(.A0 (n_87), .A1 (sh_reg[1]), .B0 (n_85), .B1 (do_o[2]),
       .Y (n_66));
  AOI22X2 g3515(.A0 (n_87), .A1 (sh_reg[9]), .B0 (n_85), .B1
       (do_o[10]), .Y (n_65));
  AOI22X2 g3516(.A0 (n_87), .A1 (sh_reg[14]), .B0 (n_85), .B1
       (do_o[15]), .Y (n_64));
  AOI22X2 g3517(.A0 (n_87), .A1 (sh_reg[13]), .B0 (n_85), .B1
       (do_o[14]), .Y (n_63));
  AOI22X2 g3518(.A0 (n_87), .A1 (sh_reg[5]), .B0 (n_85), .B1 (do_o[6]),
       .Y (n_62));
  NAND2XL g3484(.A (n_103), .B (sh_reg[9]), .Y (n_61));
  NAND2XL g3481(.A (n_103), .B (sh_reg[20]), .Y (n_60));
  NAND2XL g3482(.A (n_103), .B (sh_reg[1]), .Y (n_59));
  NAND2XL g3483(.A (n_103), .B (sh_reg[8]), .Y (n_58));
  OAI2BB1XL g3480(.A0N (do_valid_D), .A1N (do_valid_C), .B0 (n_186), .Y
       (n_57));
  NAND2XL g3485(.A (n_103), .B (sh_reg[10]), .Y (n_56));
  NAND2XL g3486(.A (n_103), .B (sh_reg[11]), .Y (n_55));
  NAND2XL g3487(.A (n_103), .B (sh_reg[18]), .Y (n_54));
  AOI2BB1X1 g3529(.A0N (n_22), .A1N (n_39), .B0 (n_34), .Y (n_53));
  NAND2XL g3489(.A (n_103), .B (sh_reg[15]), .Y (n_52));
  NAND2XL g3490(.A (n_103), .B (sh_reg[17]), .Y (n_51));
  NAND2XL g3491(.A (n_103), .B (sh_reg[23]), .Y (n_50));
  NOR2X1 g3520(.A (n_46), .B (n_21), .Y (n_49));
  AND2X1 g3522(.A (n_37), .B (state_reg[4]), .Y (n_48));
  NOR2X1 g3523(.A (n_46), .B (n_32), .Y (n_47));
  AOI2BB1X1 g3527(.A0N (n_20), .A1N (n_10), .B0 (n_46), .Y (n_45));
  NAND2XL g3488(.A (n_103), .B (sh_reg[13]), .Y (n_44));
  INVX1 g3519(.A (n_103), .Y (n_43));
  AOI22X2 g3528(.A0 (n_25), .A1 (n_35), .B0 (n_41), .B1 (n_19), .Y
       (n_42));
  NAND3X1 g3526(.A (n_36), .B (n_39), .C (state_reg[4]), .Y (n_40));
  AOI2BB1X1 g3525(.A0N (n_11), .A1N (rst), .B0 (n_29), .Y (n_38));
  INVX2 g3530(.A (n_131), .Y (n_100));
  AND2X4 g3524(.A (n_31), .B (n_186), .Y (n_103));
  OR2X1 g3532(.A (n_36), .B (n_35), .Y (n_37));
  AND2X1 g3538(.A (n_26), .B (n_15), .Y (n_34));
  AND2X2 g3533(.A (n_36), .B (n_6), .Y (n_46));
  AND2X4 g3534(.A (n_28), .B (n_186), .Y (n_85));
  AND2X4 g3521(.A (n_18), .B (n_186), .Y (spi_miso_o));
  DFFSX1 do_valid_D_reg(.SN (n_186), .CK (clk_i), .D (do_valid_C), .Q
       (do_valid_D), .QN (UNCONNECTED81));
  AND2X1 g3539(.A (n_17), .B (state_reg[2]), .Y (n_32));
  OR2X4 g3536(.A (n_13), .B (n_8), .Y (n_131));
  AND2X4 g3535(.A (n_27), .B (n_186), .Y (n_87));
  INVXL g3537(.A (n_30), .Y (n_31));
  AND3X1 g3540(.A (n_41), .B (state_reg[2]), .C (n_5), .Y (n_29));
  INVXL g3544(.A (n_27), .Y (n_28));
  OAI2BB1XL g3550(.A0N (n_39), .A1N (n_24), .B0 (n_23), .Y (n_26));
  OAI2BB1X1 g3553(.A0N (state_reg[4]), .A1N (n_24), .B0 (n_23), .Y
       (n_25));
  CLKINVX2 g3545(.A (n_22), .Y (n_36));
  NOR3X2 g3542(.A (n_20), .B (n_19), .C (state_reg[0]), .Y (n_21));
  MX2X1 g3541(.A (tx_bit_reg), .B (di_reg[23]), .S0 (preload_miso), .Y
       (n_18));
  NOR2X1 g3546(.A (n_20), .B (n_9), .Y (n_17));
  OR3X1 g3543(.A (n_12), .B (state_reg[3]), .C (n_3), .Y (n_30));
  DFFSX1 do_valid_C_reg(.SN (n_186), .CK (clk_i), .D (do_valid_B), .Q
       (do_valid_C), .QN (UNCONNECTED82));
  AND2X1 g3551(.A (n_7), .B (n_15), .Y (n_16));
  INVXL g3555(.A (n_23), .Y (n_14));
  AOI2BB1X2 g3552(.A0N (n_24), .A1N (wren), .B0 (n_12), .Y (n_13));
  NOR2X2 g3548(.A (n_11), .B (state_reg[0]), .Y (n_27));
  NAND2X2 g3549(.A (n_12), .B (n_186), .Y (n_22));
  AOI22X2 g3554(.A0 (n_9), .A1 (state_reg[2]), .B0 (state_reg[1]), .B1
       (state_reg[0]), .Y (n_10));
  OR2X2 g3559(.A (n_24), .B (n_4), .Y (n_23));
  CLKINVX2 g3560(.A (n_8), .Y (n_41));
  NAND2XL g3561(.A (n_19), .B (state_reg[3]), .Y (n_7));
  DFFSX1 do_valid_B_reg(.SN (n_186), .CK (clk_i), .D (do_valid_A), .Q
       (do_valid_B), .QN (UNCONNECTED83));
  NOR2X4 g3558(.A (n_35), .B (n_15), .Y (n_20));
  OR3X2 g3562(.A (n_6), .B (state_reg[2]), .C (n_5), .Y (n_11));
  NAND2X2 g3564(.A (n_15), .B (state_reg[3]), .Y (n_8));
  AND2X2 g3563(.A (n_19), .B (n_4), .Y (n_12));
  CLKINVX2 g3565(.A (n_19), .Y (n_24));
  DFFNSRX1 preload_miso_reg(.RN (n_0), .SN (n_186), .CKN (spi_sck_i),
       .D (1'b1), .Q (UNCONNECTED84), .QN (preload_miso));
  OR2X2 g3569(.A (n_39), .B (state_reg[4]), .Y (n_6));
  AND2X4 g3570(.A (state_reg[3]), .B (n_186), .Y (n_35));
  AND2X4 g3571(.A (n_3), .B (n_186), .Y (n_15));
  DFFSX1 do_valid_A_reg(.SN (n_186), .CK (clk_i), .D (n_2), .Q
       (do_valid_A), .QN (UNCONNECTED85));
  AND2X2 g3567(.A (n_4), .B (n_5), .Y (n_9));
  AND2X4 g3568(.A (n_1), .B (n_5), .Y (n_19));
  NOR2XL g3572(.A (spi_ssel_i), .B (rst), .Y (n_105));
  INVXL g3578(.A (do_transfer_reg), .Y (n_2));
  CLKINVX2 g3577(.A (state_reg[4]), .Y (n_3));
  INVX2 g3574(.A (state_reg[1]), .Y (n_5));
  CLKINVX8 g3580(.A (rst), .Y (n_186));
  INVXL g3575(.A (state_reg[2]), .Y (n_1));
  INVXL g3573(.A (spi_ssel_i), .Y (n_0));
  CLKINVX2 g3576(.A (state_reg[0]), .Y (n_4));
  INVX2 g3579(.A (state_reg[3]), .Y (n_39));
endmodule

